#!/usr/bin/env python3
"""Audit (without solving) the Device-A Figure-3H scan registration.

The earlier Device-A contract accepted Figure 3H as an input but never used
its pixels.  It instead moved the source along the normal of a non-boundary
polygon chord.  This audit freezes the visible Figure-3H scan line and makes
the missing Figure-3H-to-Figure-2 registration explicit.  It deliberately
does not invent an absolute laser coordinate.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


# Manual picks on the 600-dpi crop generated by the command stored below.
FIG3H_LEFT_PANEL_BOUNDS_PX = np.asarray([[125.0, 251.0], [680.0, 720.0]])
FIG3H_SCALE_BAR_PX = np.asarray([[263.0, 281.0], [375.0, 281.0]])
FIG3H_BLACK_SCAN_LINE_PX = np.asarray([[217.0, 252.0], [217.0, 719.0]])
FIG3H_WHITE_DASHED_REGION_PX = np.asarray(
    [[150.0, 365.0], [288.0, 365.0], [288.0, 554.0], [150.0, 554.0]]
)

# The old Figure-2 digitizer's full left-side chord.  Vertices 5 and 6 lie on
# the actual polygon boundary between these endpoints, so 4->7 itself is not
# a literal boundary segment.
OLD_CHORD_ENDPOINTS_FIG2_PX = np.asarray([[141.0, 628.0], [247.0, 484.0]])
OLD_INWARD_NORMAL_CODE = np.asarray([0.8053368838936223, -0.5928174284216942])


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def unit(vector: np.ndarray) -> np.ndarray:
    vector = np.asarray(vector, float)
    return vector / np.linalg.norm(vector)


def acute_angle_deg(first: np.ndarray, second: np.ndarray) -> float:
    cosine = abs(float(np.dot(unit(first), unit(second))))
    return float(np.degrees(np.arccos(np.clip(cosine, -1.0, 1.0))))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fig3h-crop", type=Path, required=True)
    parser.add_argument("--old-geometry-json", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    return parser.parse_args()


def draw_rgb(ax: plt.Axes, image: np.ndarray) -> None:
    """Draw an RGB crop in literal pixel-edge coordinates."""

    height, width = image.shape[:2]
    rgb = image[..., :3]
    ax.pcolormesh(
        np.arange(width + 1),
        np.arange(height + 1),
        rgb,
        shading="flat",
        rasterized=True,
    )
    ax.set_xlim(0.0, float(width))
    ax.set_ylim(float(height), 0.0)


def main() -> int:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    old = json.loads(args.old_geometry_json.read_text())
    image = plt.imread(args.fig3h_crop)

    scan_image_direction = unit(
        FIG3H_BLACK_SCAN_LINE_PX[1] - FIG3H_BLACK_SCAN_LINE_PX[0]
    )
    old_normal_image_direction = unit(
        np.asarray([OLD_INWARD_NORMAL_CODE[0], -OLD_INWARD_NORMAL_CODE[1]])
    )
    direction_mismatch = acute_angle_deg(
        scan_image_direction, old_normal_image_direction
    )
    scale_length_px = float(
        np.linalg.norm(FIG3H_SCALE_BAR_PX[1] - FIG3H_SCALE_BAR_PX[0])
    )
    # The black bar is treated as 10 um only as an explicit figure-reading
    # assumption.  It is consistent with the approximately 40-um horizontal
    # range in Fig. 3I, but the crop contains no printed scale-bar label.
    assumed_scale_bar_um = 10.0
    px_per_um = scale_length_px / assumed_scale_bar_um
    scan_length_um = float(
        np.linalg.norm(
            FIG3H_BLACK_SCAN_LINE_PX[1] - FIG3H_BLACK_SCAN_LINE_PX[0]
        )
        / px_per_um
    )

    fig, ax = plt.subplots(figsize=(9.0, 8.0), constrained_layout=True)
    draw_rgb(ax, image)
    panel = FIG3H_LEFT_PANEL_BOUNDS_PX
    ax.add_patch(
        plt.Rectangle(
            panel[0],
            *(panel[1] - panel[0]),
            fill=False,
            edgecolor="tab:orange",
            linewidth=2.0,
            label="E||a panel bounds",
        )
    )
    closed_white = np.vstack(
        (FIG3H_WHITE_DASHED_REGION_PX, FIG3H_WHITE_DASHED_REGION_PX[0])
    )
    ax.plot(
        closed_white[:, 0],
        closed_white[:, 1],
        color="white",
        linewidth=2.0,
        label="visible white dashed region",
    )
    ax.plot(
        FIG3H_BLACK_SCAN_LINE_PX[:, 0],
        FIG3H_BLACK_SCAN_LINE_PX[:, 1],
        color="magenta",
        linewidth=2.5,
        label="Fig. 3H black scan line",
    )
    ax.plot(
        FIG3H_SCALE_BAR_PX[:, 0],
        FIG3H_SCALE_BAR_PX[:, 1],
        color="cyan",
        linewidth=3.0,
        label="visible scale bar",
    )
    ax.set_xlabel("Figure-3H crop x (pixel)")
    ax.set_ylabel("Figure-3H crop y (pixel)")
    ax.set_title("Device A Fig. 3H scan-line audit (no coordinate invention)")
    ax.legend(loc="lower right", fontsize=8)
    fig.savefig(args.output_dir / "DEVICE_A_FIG3H_SCAN_LINE_AUDIT.png", dpi=220)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(7.2, 5.0), constrained_layout=True)
    origin = np.zeros(2)
    ax.quiver(
        *origin,
        *scan_image_direction,
        angles="xy",
        scale_units="xy",
        scale=1.0,
        color="black",
        label="actual Fig. 3H scan direction",
    )
    ax.quiver(
        *origin,
        *old_normal_image_direction,
        angles="xy",
        scale_units="xy",
        scale=1.0,
        color="tab:red",
        label="old simulated chord-normal direction",
    )
    ax.set_xlim(-0.15, 1.15)
    ax.set_ylim(-0.15, 1.15)
    ax.set_aspect("equal")
    ax.grid(alpha=0.25)
    ax.set_xlabel("image +x")
    ax.set_ylabel("image +y (down)")
    ax.set_title(f"Direction mismatch = {direction_mismatch:.2f} degrees")
    ax.legend(loc="upper left", fontsize=8)
    fig.savefig(args.output_dir / "DEVICE_A_OLD_NEW_SCAN_DIRECTION.png", dpi=220)
    plt.close(fig)

    payload = {
        "status": "BLOCKED_FIG3H_TO_FIG2_ABSOLUTE_REGISTRATION_UNDERDETERMINED",
        "scope": "offline figure-coordinate audit; no FDTD, thermal, PTE, or fitting",
        "fig3h_input": {
            "path": str(args.fig3h_crop.resolve()),
            "size_bytes": args.fig3h_crop.stat().st_size,
            "sha256": sha256(args.fig3h_crop),
            "render_dpi": 600,
            "generation_command": (
                "pdftoppm -f 6 -l 6 -r 600 -png -singlefile PAPER page6; "
                "crop=1900x1900+450+2300"
            ),
        },
        "visible_pixel_contract": {
            "left_panel_bounds_px": FIG3H_LEFT_PANEL_BOUNDS_PX.tolist(),
            "black_scan_line_endpoints_px": FIG3H_BLACK_SCAN_LINE_PX.tolist(),
            "black_scan_line_unit_direction_image_xy": scan_image_direction.tolist(),
            "white_dashed_region_vertices_px": FIG3H_WHITE_DASHED_REGION_PX.tolist(),
            "scale_bar_endpoints_px": FIG3H_SCALE_BAR_PX.tolist(),
            "scale_bar_length_px": scale_length_px,
            "assumed_scale_bar_length_um": assumed_scale_bar_um,
            "scale_assumption_status": (
                "EXPLICIT_FIGURE_READING_ASSUMPTION; the crop does not print "
                "the scale-bar label"
            ),
            "pixels_per_um_under_assumption": px_per_um,
            "scan_line_length_um_under_assumption": scan_length_um,
        },
        "old_contract_audit": {
            "old_geometry_json": str(args.old_geometry_json.resolve()),
            "old_geometry_sha256": sha256(args.old_geometry_json),
            "old_source_rule": old.get("beam_center_rule"),
            "old_source_center_code_um": old.get(
                "pre_registered_beam_center_code_um"
            ),
            "old_chord_endpoint_vertices": old.get(
                "off_axis_edge_vertex_indices"
            ),
            "old_chord_endpoints_fig2_px": OLD_CHORD_ENDPOINTS_FIG2_PX.tolist(),
            "old_chord_is_literal_polygon_edge": False,
            "intermediate_actual_polygon_vertices": [5, 6],
            "old_chord_normal_unit_direction_image_xy": (
                old_normal_image_direction.tolist()
            ),
            "direction_mismatch_vs_fig3h_scan_deg": direction_mismatch,
            "fig3h_pixels_used_by_old_coordinate_calculation": False,
        },
        "registration_gate": {
            "fig3h_scan_line_digitized": True,
            "fig3h_to_fig2_shared_fiducials_published": False,
            "absolute_source_coordinate_identified": False,
            "old_s2_s3_s4_um_sweep_is_fig3h_scan": False,
            "new_FDTD_authorized_by_this_gate": False,
        },
        "required_next_registration": (
            "digitize at least two non-collinear structural fiducials visible "
            "in both Fig. 2D and Fig. 3H, or report a named approximate affine "
            "registration with uncertainty; do not reuse the old 3-um chord-"
            "normal point as an experimental coordinate"
        ),
    }
    (args.output_dir / "device_a_fig3h_registration_audit.json").write_text(
        json.dumps(payload, indent=2) + "\n"
    )
    report = f"""# Device-A Figure 3H registration audit

Status: `{payload['status']}`

This is an offline coordinate audit. It did not execute Maxwell, thermal,
PTE, adjoint, AD-FD, or optimization code.

## Definite finding

The previous geometry script accepted the Figure-3H crop but did not use a
single Figure-3H pixel in its source-coordinate calculation. It chose a point
3 um inward from the normal of polygon vertices 4 and 7. Those vertices are
not adjacent: actual boundary vertices 5 and 6 lie between them.

The visible Figure-3H scan line is nearly vertical. Its acute directional
difference from the previously simulated chord normal is
`{direction_mismatch:.3f} deg`. Therefore the completed old `s=2,3,4 um`
sweep is a valid numerical source-position sensitivity study, but it is not
a registered reproduction of the Figure-3H black dashed line.

## What is still missing

The paper does not publish absolute stage coordinates or enough explicitly
labelled shared fiducials to map this crop to the Figure-2 digitized polygon
without an additional image-registration assumption. The black scan line is
now digitized, but no new absolute source point is promoted and no new FDTD is
started by this checkpoint.
"""
    (args.output_dir / "DEVICE_A_FIG3H_REGISTRATION_AUDIT.md").write_text(report)
    print(json.dumps(payload, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
