#!/usr/bin/env python3
"""Map Lumerical 11 um Q into the current explicit-boundary thermal FVM.

The optical artifact is generated by ``run_lumerical_device_a_ir_q.py``.
This script intentionally uses the *expanded production thermal model*:

* explicit bulk Si, 285 nm SiO2, TaIrTe4, and air cells;
* TaIrTe4/SiO2, TaIrTe4/air, and SiO2/Si interface resistances;
* fixed far-x/y and bottom numerical boundaries; and
* exposed top-surface convection.

Those assumptions are not mislabeled as the paper's reduced Robin model.
The flake and contacts are explicit, documented approximations to Device A.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.path import Path as PolygonPath
import numpy as np
from scipy import sparse
from scipy.sparse import linalg as spla


HERE = Path(__file__).resolve().parent
REPOSITORY = HERE.parents[2]
FVM_DIR = HERE.parent / "photothermal_stage1"
for location in (REPOSITORY, FVM_DIR):
    if str(location) not in sys.path:
        sys.path.insert(0, str(location))

from anisotropic_heat_fvm import (  # noqa: E402
    assemble_steady_diagonal_kappa,
    solve_assembled_thermal_system,
)
from photothermal_pte.finite_inverse_design.finite_q_mapping import (  # noqa: E402
    apply_material_intersection_density_separable,
    build_conservative_embedding_remap,
    build_material_overlap_remap,
    nodal_control_volume_edges,
)
from photothermal_pte.validation.paper_ir_sanity.coordinate_plot import (  # noqa: E402
    cell_field,
    strict_centered_xy_mask,
)


T_BATH_K = 300.0
THICKNESS_M = 130.0e-9
SIO2_THICKNESS_M = 285.0e-9
AIR_HEIGHT_M = 600.0e-9
KAPPA_TAIRTE4_LAB_W_MK = np.asarray([3.8, 14.4, 1.0])  # lab x=b, y=a
KAPPA_SIO2_W_MK = 1.38
KAPPA_SI_W_MK = 145.0
KAPPA_AIR_W_MK = 0.026
G_TAIRTE4_AIR_W_M2K = 1.0
G_TAIRTE4_THERMALLY_GROWN_SIO2_W_M2K = 7.37e6
G_TAIRTE4_EVAPORATED_SIO2_W_M2K = 7.37e4
# Backward-compatible name used by frozen controls and imports.
G_TAIRTE4_SIO2_W_M2K = G_TAIRTE4_THERMALLY_GROWN_SIO2_W_M2K
G_SIO2_SI_W_M2K = 1.1e9
H_EXPOSED_W_M2K = 10.0
SIGMA_LAB_S_M = np.asarray([1.10e5, 4.91e5])  # b, a
SEEBECK_LAB_V_K = np.asarray([27.0e-6, -6.0e-6])  # b, a
DEFAULT_EXPERIMENTAL_INCIDENT_POWER_W = 285.0e-6

FLAKE_VERTICES_UM = np.asarray(
    [
        [-11.0, -10.0],
        [12.0, -10.0],
        [12.0, 10.0],
        [-6.0, 10.0],
        [-6.0, 6.0],
        [-11.0, 1.0],
    ]
)
TOP_CONTACT_SEGMENT_UM: np.ndarray | None = None
BOTTOM_CONTACT_SEGMENT_UM: np.ndarray | None = None


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def jsonable(value: Any) -> Any:
    """Convert NumPy-backed audit metadata without changing numeric values."""
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, dict):
        return {key: jsonable(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [jsonable(item) for item in value]
    return value


def growing_positions(
    length_m: float,
    initial_step_m: float,
    maximum_step_m: float,
    growth: float = 1.4,
) -> np.ndarray:
    values = [0.0]
    step = initial_step_m
    while values[-1] + step < length_m:
        values.append(values[-1] + step)
        step = min(maximum_step_m, growth * step)
    values.append(length_m)
    return np.unique(np.asarray(values))


def lateral_edges(
    domain_m: float,
    core_step_m: float,
    core_min: float,
    core_max: float,
) -> np.ndarray:
    cells = int(round((core_max - core_min) / core_step_m))
    if not np.isclose(cells * core_step_m, core_max - core_min):
        raise ValueError("core step must divide the Device-A core bounds")
    core = np.linspace(core_min, core_max, cells + 1)
    half = 0.5 * domain_m
    if half <= core_max:
        raise ValueError("thermal domain must extend beyond Device A")
    outer_low = growing_positions(
        core_min + half,
        initial_step_m=core_step_m,
        maximum_step_m=1.0e-6,
    )[1:]
    outer_high = growing_positions(
        half - core_max,
        initial_step_m=core_step_m,
        maximum_step_m=1.0e-6,
    )[1:]
    return np.concatenate(
        (core_min - outer_low[::-1], core, core_max + outer_high)
    )


def z_edges(si_depth_m: float, flake_dz_m: float) -> np.ndarray:
    if not np.isclose(round(THICKNESS_M / flake_dz_m) * flake_dz_m, THICKNESS_M):
        raise ValueError("flake dz must divide 130 nm")
    si_top = -(THICKNESS_M + SIO2_THICKNESS_M)
    si = si_top - growing_positions(
        si_depth_m, initial_step_m=25e-9, maximum_step_m=0.5e-6, growth=1.35
    )[::-1]
    oxide = np.linspace(si_top, -THICKNESS_M, 20)
    flake = np.linspace(
        -THICKNESS_M,
        0.0,
        int(round(THICKNESS_M / flake_dz_m)) + 1,
    )
    air = np.linspace(0.0, AIR_HEIGHT_M, 7)
    edges = np.concatenate((si, oxide[1:], flake[1:], air[1:]))
    if np.any(np.diff(edges) <= 0):
        raise RuntimeError("z grid is not strictly increasing")
    return edges


def polygon_mask(x_m: np.ndarray, y_m: np.ndarray) -> np.ndarray:
    xx, yy = np.meshgrid(x_m, y_m, indexing="ij")
    points = np.column_stack((xx.ravel(), yy.ravel()))
    return PolygonPath(FLAKE_VERTICES_UM * 1e-6).contains_points(
        points, radius=1e-15
    ).reshape(xx.shape)


@dataclass(frozen=True)
class Geometry:
    x_edges_m: np.ndarray
    y_edges_m: np.ndarray
    z_edges_m: np.ndarray
    material_id: np.ndarray
    flake_mask: np.ndarray
    kappa_W_mK: np.ndarray
    interface_resistance_m2K_W: dict[str, np.ndarray]


def build_geometry(
    *,
    domain_m: float,
    si_depth_m: float,
    core_step_m: float,
    flake_dz_m: float,
    tairte4_sio2_G_W_m2K: float = G_TAIRTE4_SIO2_W_M2K,
) -> Geometry:
    if not np.isfinite(tairte4_sio2_G_W_m2K) or tairte4_sio2_G_W_m2K <= 0.0:
        raise ValueError("TaIrTe4/SiO2 interface G must be finite and positive")
    if np.max(np.abs(FLAKE_VERTICES_UM)) > 0.5 * domain_m * 1e6:
        core_bounds_um = {"x": (-12.0, 12.0), "y": (-12.0, 12.0)}
    else:
        core_bounds_um = {}
        for axis, column in (("x", 0), ("y", 1)):
            low = np.floor(
                (np.min(FLAKE_VERTICES_UM[:, column]) - 1.0)
                * 1e-6
                / core_step_m
            ) * core_step_m
            high = np.ceil(
                (np.max(FLAKE_VERTICES_UM[:, column]) + 1.0)
                * 1e-6
                / core_step_m
            ) * core_step_m
            core_bounds_um[axis] = (float(low * 1e6), float(high * 1e6))
    x_edges = lateral_edges(
        domain_m,
        core_step_m,
        *(value * 1e-6 for value in core_bounds_um["x"]),
    )
    y_edges = lateral_edges(
        domain_m,
        core_step_m,
        *(value * 1e-6 for value in core_bounds_um["y"]),
    )
    z_edge = z_edges(si_depth_m, flake_dz_m)
    x = 0.5 * (x_edges[:-1] + x_edges[1:])
    y = 0.5 * (y_edges[:-1] + y_edges[1:])
    z = 0.5 * (z_edge[:-1] + z_edge[1:])
    shape = (x.size, y.size, z.size)
    material = np.zeros(shape, np.uint8)  # air
    si = z < -(THICKNESS_M + SIO2_THICKNESS_M)
    oxide = (z > -(THICKNESS_M + SIO2_THICKNESS_M)) & (z < -THICKNESS_M)
    flake_z = (z > -THICKNESS_M) & (z < 0.0)
    material[:, :, si] = 1
    material[:, :, oxide] = 2
    flake_xy = polygon_mask(x, y)
    flake = flake_xy[:, :, None] & flake_z[None, None, :]
    material[flake] = 3

    kappa = np.full((*shape, 3), KAPPA_AIR_W_MK)
    kappa[material == 1] = KAPPA_SI_W_MK
    kappa[material == 2] = KAPPA_SIO2_W_MK
    kappa[material == 3] = KAPPA_TAIRTE4_LAB_W_MK
    rx = np.zeros((shape[0] - 1, shape[1], shape[2]))
    ry = np.zeros((shape[0], shape[1] - 1, shape[2]))
    rz = np.zeros((shape[0], shape[1], shape[2] - 1))
    left, right = material[:-1], material[1:]
    rx[((left == 3) & (right == 0)) | ((left == 0) & (right == 3))] = (
        1.0 / G_TAIRTE4_AIR_W_M2K
    )
    low, high = material[:, :-1], material[:, 1:]
    ry[((low == 3) & (high == 0)) | ((low == 0) & (high == 3))] = (
        1.0 / G_TAIRTE4_AIR_W_M2K
    )
    lower, upper = material[:, :, :-1], material[:, :, 1:]
    rz[((lower == 1) & (upper == 2)) | ((lower == 2) & (upper == 1))] = (
        1.0 / G_SIO2_SI_W_M2K
    )
    rz[((lower == 2) & (upper == 3)) | ((lower == 3) & (upper == 2))] = (
        1.0 / tairte4_sio2_G_W_m2K
    )
    rz[((lower == 3) & (upper == 0)) | ((lower == 0) & (upper == 3))] = (
        1.0 / G_TAIRTE4_AIR_W_M2K
    )
    return Geometry(
        x_edges,
        y_edges,
        z_edge,
        material,
        flake,
        kappa,
        {"x": rx, "y": ry, "z": rz},
    )


def reduced_flake_geometry(
    expanded: Geometry,
    q_expanded: np.ndarray,
) -> tuple[Geometry, np.ndarray]:
    """Extract the paper Eq. S4 sheet-like Robin reference from one grid."""
    selected_z = np.flatnonzero(np.any(expanded.flake_mask, axis=(0, 1)))
    if selected_z.size == 0 or not np.all(np.diff(selected_z) == 1):
        raise RuntimeError("cannot identify contiguous flake z cells")
    start, stop = int(selected_z[0]), int(selected_z[-1] + 1)
    z_edges = expanded.z_edges_m[start : stop + 1]
    flake_xy = np.any(expanded.flake_mask, axis=2)
    flake = np.broadcast_to(
        flake_xy[:, :, None],
        (flake_xy.shape[0], flake_xy.shape[1], selected_z.size),
    ).copy()
    material = np.zeros(flake.shape, np.uint8)
    material[flake] = 3
    kappa = np.ones((*flake.shape, 3), float)
    kappa[flake] = KAPPA_TAIRTE4_LAB_W_MK
    resistances = {
        "x": np.zeros((flake.shape[0] - 1, flake.shape[1], flake.shape[2])),
        "y": np.zeros((flake.shape[0], flake.shape[1] - 1, flake.shape[2])),
        "z": np.zeros((flake.shape[0], flake.shape[1], flake.shape[2] - 1)),
    }
    return (
        Geometry(
            expanded.x_edges_m,
            expanded.y_edges_m,
            z_edges,
            material,
            flake,
            kappa,
            resistances,
        ),
        q_expanded[:, :, start:stop],
    )


def solve_weighting_potential(
    x_edges_m: np.ndarray,
    y_edges_m: np.ndarray,
    flake_xy: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, dict[str, Any]]:
    """Finite-volume Eq. S7 with approximate full-width top/bottom contacts."""
    x = 0.5 * (x_edges_m[:-1] + x_edges_m[1:])
    y = 0.5 * (y_edges_m[:-1] + y_edges_m[1:])
    dx, dy = np.diff(x_edges_m), np.diff(y_edges_m)
    ids = np.full(flake_xy.shape, -1, np.int64)
    ids[flake_xy] = np.arange(np.count_nonzero(flake_xy))
    n = int(np.count_nonzero(flake_xy))
    diagonal = np.zeros(n)
    rows: list[np.ndarray] = []
    cols: list[np.ndarray] = []
    vals: list[np.ndarray] = []
    for axis in (0, 1):
        if axis == 0:
            lhs, rhs = ids[:-1], ids[1:]
            conductance = (
                2.0 * dy[None, :] / (dx[:-1, None] + dx[1:, None])
            )
        else:
            lhs, rhs = ids[:, :-1], ids[:, 1:]
            conductance = (
                2.0 * dx[:, None] / (dy[None, :-1] + dy[None, 1:])
            )
        connected = (lhs >= 0) & (rhs >= 0)
        left_id, right_id = lhs[connected], rhs[connected]
        g = np.broadcast_to(conductance, lhs.shape)[connected]
        np.add.at(diagonal, left_id, g)
        np.add.at(diagonal, right_id, g)
        rows += [left_id, right_id]
        cols += [right_id, left_id]
        vals += [-g, -g]

    # Contacts inferred from Fig. 2A: top/bottom bars cover broad exterior
    # boundary segments. Detect the exterior faces topologically so the
    # contract does not depend on cell-centre equality at +/-9.9 um.
    neighbour_above = np.zeros_like(flake_xy)
    neighbour_above[:, :-1] = flake_xy[:, 1:]
    neighbour_below = np.zeros_like(flake_xy)
    neighbour_below[:, 1:] = flake_xy[:, :-1]
    top_boundary = flake_xy & ~neighbour_above
    bottom_boundary = flake_xy & ~neighbour_below
    if TOP_CONTACT_SEGMENT_UM is None or BOTTOM_CONTACT_SEGMENT_UM is None:
        top = top_boundary & (y[None, :] > 8.0e-6) & (x[:, None] > -5.8e-6)
        bottom = bottom_boundary & (y[None, :] < -8.0e-6) & (x[:, None] > -10.5e-6)
        contact_source = "legacy approximate Figure-2 bounds"
    else:
        top_x = np.sort(np.asarray(TOP_CONTACT_SEGMENT_UM, float)[:, 0]) * 1e-6
        bottom_x = np.sort(np.asarray(BOTTOM_CONTACT_SEGMENT_UM, float)[:, 0]) * 1e-6
        top = top_boundary & (x[:, None] >= top_x[0]) & (x[:, None] <= top_x[-1])
        bottom = (
            bottom_boundary
            & (x[:, None] >= bottom_x[0])
            & (x[:, None] <= bottom_x[-1])
        )
        contact_source = "frozen Figure-2 digitized contact segments"
    if not np.any(top) or not np.any(bottom):
        raise RuntimeError(
            f"contact discretization failed: top={np.count_nonzero(top)}, "
            f"bottom={np.count_nonzero(bottom)}"
        )
    load = np.zeros(n)
    contact_half_widths: dict[str, np.ndarray] = {}
    for label, selected, value in (
        ("top", top, 1.0),
        ("bottom", bottom, 0.0),
    ):
        flat = ids[selected]
        area = np.broadcast_to(dx[:, None], ids.shape)[selected]
        half_width = 0.5 * np.broadcast_to(dy[None, :], ids.shape)[selected]
        contact_half_widths[label] = half_width
        g = area / half_width
        np.add.at(diagonal, flat, g)
        np.add.at(load, flat, g * value)
    matrix = sparse.diags(diagonal) + sparse.coo_matrix(
        (np.concatenate(vals), (np.concatenate(rows), np.concatenate(cols))),
        shape=(n, n),
    ).tocsr()
    psi_active = spla.spsolve(matrix.tocsc(), load)
    residual = np.linalg.norm(matrix @ psi_active - load) / max(
        np.linalg.norm(load), np.finfo(float).tiny
    )
    psi = np.full(ids.shape, np.nan)
    psi[flake_xy] = psi_active
    grad_x, grad_y = cell_gradient(psi, flake_xy, x, y)
    return psi, grad_x, grad_y, {
        "top_contact_cells": int(np.count_nonzero(top)),
        "bottom_contact_cells": int(np.count_nonzero(bottom)),
        "minimum_psi": float(np.nanmin(psi)),
        "maximum_psi": float(np.nanmax(psi)),
        "linear_residual_relative": float(residual),
        "top_contact_half_width_m": {
            "minimum": float(np.min(contact_half_widths["top"])),
            "maximum": float(np.max(contact_half_widths["top"])),
        },
        "bottom_contact_half_width_m": {
            "minimum": float(np.min(contact_half_widths["bottom"])),
            "maximum": float(np.max(contact_half_widths["bottom"])),
        },
        "geometry_status": contact_source,
    }


def audit_two_terminal_resistance(
    x_edges_m: np.ndarray,
    y_edges_m: np.ndarray,
    flake_xy: np.ndarray,
    *,
    thickness_m: float = THICKNESS_M,
    measured_resistance_ohm: float = 213.0,
) -> dict[str, Any]:
    """Predict the digitized flake's sheet resistance without fitting it.

    This is deliberately separate from the paper's Laplace weighting-field
    operator.  It solves div(sigma grad(V))=0 with x=b and y=a, applies one
    volt across the same digitized contacts, and integrates terminal current.
    Contact resistance is not added because it was not published.
    """
    x = 0.5 * (x_edges_m[:-1] + x_edges_m[1:])
    y = 0.5 * (y_edges_m[:-1] + y_edges_m[1:])
    dx, dy = np.diff(x_edges_m), np.diff(y_edges_m)
    ids = np.full(flake_xy.shape, -1, np.int64)
    ids[flake_xy] = np.arange(np.count_nonzero(flake_xy))
    count = int(np.count_nonzero(flake_xy))
    diagonal = np.zeros(count)
    load = np.zeros(count)
    rows: list[np.ndarray] = []
    cols: list[np.ndarray] = []
    vals: list[np.ndarray] = []
    for axis, conductivity in enumerate(SIGMA_LAB_S_M):
        if axis == 0:
            lhs, rhs = ids[:-1], ids[1:]
            conductance = (
                conductivity
                * thickness_m
                * 2.0
                * dy[None, :]
                / (dx[:-1, None] + dx[1:, None])
            )
        else:
            lhs, rhs = ids[:, :-1], ids[:, 1:]
            conductance = (
                conductivity
                * thickness_m
                * 2.0
                * dx[:, None]
                / (dy[None, :-1] + dy[None, 1:])
            )
        connected = (lhs >= 0) & (rhs >= 0)
        left_id, right_id = lhs[connected], rhs[connected]
        g = np.broadcast_to(conductance, lhs.shape)[connected]
        np.add.at(diagonal, left_id, g)
        np.add.at(diagonal, right_id, g)
        rows += [left_id, right_id]
        cols += [right_id, left_id]
        vals += [-g, -g]

    neighbour_above = np.zeros_like(flake_xy)
    neighbour_above[:, :-1] = flake_xy[:, 1:]
    neighbour_below = np.zeros_like(flake_xy)
    neighbour_below[:, 1:] = flake_xy[:, :-1]
    top_boundary = flake_xy & ~neighbour_above
    bottom_boundary = flake_xy & ~neighbour_below
    if TOP_CONTACT_SEGMENT_UM is None or BOTTOM_CONTACT_SEGMENT_UM is None:
        top = top_boundary & (y[None, :] > 8.0e-6) & (x[:, None] > -5.8e-6)
        bottom = bottom_boundary & (y[None, :] < -8.0e-6) & (x[:, None] > -10.5e-6)
        contact_source = "legacy approximate Figure-2 bounds"
    else:
        top_x = np.sort(np.asarray(TOP_CONTACT_SEGMENT_UM, float)[:, 0]) * 1e-6
        bottom_x = np.sort(np.asarray(BOTTOM_CONTACT_SEGMENT_UM, float)[:, 0]) * 1e-6
        top = top_boundary & (x[:, None] >= top_x[0]) & (x[:, None] <= top_x[-1])
        bottom = (
            bottom_boundary
            & (x[:, None] >= bottom_x[0])
            & (x[:, None] <= bottom_x[-1])
        )
        contact_source = "frozen Figure-2 digitized contact segments"
    if not np.any(top) or not np.any(bottom):
        raise RuntimeError("resistance-audit contact discretization failed")

    terminal_faces: dict[str, tuple[np.ndarray, np.ndarray]] = {}
    for label, selected, voltage in (
        ("top", top, 1.0),
        ("bottom", bottom, 0.0),
    ):
        flat = ids[selected]
        face_width = np.broadcast_to(dx[:, None], ids.shape)[selected]
        half_distance = 0.5 * np.broadcast_to(dy[None, :], ids.shape)[selected]
        g = SIGMA_LAB_S_M[1] * thickness_m * face_width / half_distance
        np.add.at(diagonal, flat, g)
        np.add.at(load, flat, g * voltage)
        terminal_faces[label] = (flat, g)
    matrix = sparse.diags(diagonal) + sparse.coo_matrix(
        (np.concatenate(vals), (np.concatenate(rows), np.concatenate(cols))),
        shape=(count, count),
    ).tocsr()
    voltage = spla.spsolve(matrix.tocsc(), load)
    residual = np.linalg.norm(matrix @ voltage - load) / max(
        np.linalg.norm(load), np.finfo(float).tiny
    )
    top_ids, top_g = terminal_faces["top"]
    bottom_ids, bottom_g = terminal_faces["bottom"]
    current_in_A = float(np.sum(top_g * (1.0 - voltage[top_ids])))
    current_out_A = float(np.sum(bottom_g * voltage[bottom_ids]))
    resistance_ohm = 1.0 / current_in_A
    balance = abs(current_in_A - current_out_A) / max(
        abs(current_in_A), abs(current_out_A), np.finfo(float).tiny
    )
    relative_difference = abs(resistance_ohm - measured_resistance_ohm) / measured_resistance_ohm
    return {
        "purpose": (
            "absolute-current geometry audit only; no empirical conductivity "
            "or PTE-current rescaling is applied"
        ),
        "axis_mapping": "x=b, y=a",
        "sigma_x_y_S_m": SIGMA_LAB_S_M.tolist(),
        "thickness_m": thickness_m,
        "contact_geometry": contact_source,
        "contact_resistance_included": False,
        "applied_voltage_V": 1.0,
        "predicted_terminal_current_A": current_in_A,
        "predicted_resistance_ohm": resistance_ohm,
        "published_measured_device_A_resistance_ohm": measured_resistance_ohm,
        "relative_difference_vs_measured": relative_difference,
        "terminal_current_balance_relative_error": balance,
        "linear_residual_relative": float(residual),
        "absolute_current_geometry_gate_lt_10pct": bool(relative_difference < 0.10),
        "interpretation": (
            "a failure blocks certification of absolute PTE-current magnitude "
            "because exact CAD/contact resistance are unpublished; it does not "
            "invalidate a separately converged polarization ratio"
        ),
    }


def cell_gradient(
    field: np.ndarray,
    mask: np.ndarray,
    x_m: np.ndarray,
    y_m: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    gx = np.zeros_like(field)
    gy = np.zeros_like(field)
    for i, j in zip(*np.nonzero(mask)):
        if i > 0 and i + 1 < field.shape[0] and mask[i - 1, j] and mask[i + 1, j]:
            gx[i, j] = (field[i + 1, j] - field[i - 1, j]) / (x_m[i + 1] - x_m[i - 1])
        elif i + 1 < field.shape[0] and mask[i + 1, j]:
            gx[i, j] = (field[i + 1, j] - field[i, j]) / (x_m[i + 1] - x_m[i])
        elif i > 0 and mask[i - 1, j]:
            gx[i, j] = (field[i, j] - field[i - 1, j]) / (x_m[i] - x_m[i - 1])
        if j > 0 and j + 1 < field.shape[1] and mask[i, j - 1] and mask[i, j + 1]:
            gy[i, j] = (field[i, j + 1] - field[i, j - 1]) / (y_m[j + 1] - y_m[j - 1])
        elif j + 1 < field.shape[1] and mask[i, j + 1]:
            gy[i, j] = (field[i, j + 1] - field[i, j]) / (y_m[j + 1] - y_m[j])
        elif j > 0 and mask[i, j - 1]:
            gy[i, j] = (field[i, j] - field[i, j - 1]) / (y_m[j] - y_m[j - 1])
    return gx, gy


def strict_centered_cell_gradient(
    field: np.ndarray,
    mask: np.ndarray,
    x_m: np.ndarray,
    y_m: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Central x/y gradient with missing four-neighbour stencils masked."""

    values = np.asarray(field, float)
    valid = strict_centered_xy_mask(mask)
    gx = np.full_like(values, np.nan)
    gy = np.full_like(values, np.nan)
    ii, jj = np.nonzero(valid)
    gx[ii, jj] = (
        values[ii + 1, jj] - values[ii - 1, jj]
    ) / (x_m[ii + 1] - x_m[ii - 1])
    gy[ii, jj] = (
        values[ii, jj + 1] - values[ii, jj - 1]
    ) / (y_m[jj + 1] - y_m[jj - 1])
    return gx, gy, valid


def measure_weighted_mean(
    values: np.ndarray,
    mask: np.ndarray,
    measure: np.ndarray,
) -> float:
    """Return a literal area/volume weighted mean on ``mask``."""
    field = np.asarray(values, float)
    selected = np.asarray(mask, bool)
    weights = np.broadcast_to(np.asarray(measure, float), field.shape)
    if field.shape != selected.shape or not np.any(selected):
        raise ValueError("weighted mean needs matching nonempty values/mask")
    denominator = float(np.sum(weights[selected]))
    if denominator <= 0.0:
        raise ValueError("weighted mean has nonpositive total measure")
    return float(np.sum(field[selected] * weights[selected]) / denominator)


def straight_edge_temperature_metrics(
    temperature_K: np.ndarray,
    geometry: Geometry,
    *,
    edge_window_um: float = 10.0,
) -> tuple[dict[str, Any], dict[str, np.ndarray]]:
    """Measure the just-inside normal gradient of the y=x half-plane edge."""
    x = 0.5 * (geometry.x_edges_m[:-1] + geometry.x_edges_m[1:])
    y = 0.5 * (geometry.y_edges_m[:-1] + geometry.y_edges_m[1:])
    dz = np.diff(geometry.z_edges_m)
    flake_z = np.flatnonzero(np.any(geometry.flake_mask, axis=(0, 1)))
    if flake_z.size == 0:
        raise RuntimeError("straight-edge control has no TaIrTe4 cells")
    thickness = float(np.sum(dz[flake_z]))
    average = np.sum(
        temperature_K[:, :, flake_z] * dz[flake_z][None, None, :],
        axis=2,
    ) / thickness
    mask = np.any(geometry.flake_mask, axis=2)
    fixed_roi = (
        mask
        & (np.abs(x[:, None]) <= 12.0e-6)
        & (np.abs(y[None, :]) <= 12.0e-6)
    )
    grad_x, grad_y, centered_valid = strict_centered_cell_gradient(
        average,
        mask,
        x,
        y,
    )
    # TaIrTe4 is y<=x; the outward normal toward air is (-x,+y)/sqrt(2).
    normal = np.asarray([-1.0, 1.0]) / np.sqrt(2.0)
    tangent_coordinate = (x[:, None] + y[None, :]) / np.sqrt(2.0)
    normal_coordinate = (-x[:, None] + y[None, :]) / np.sqrt(2.0)
    grad_normal = normal[0] * grad_x + normal[1] * grad_y
    tangent = np.asarray([1.0, 1.0]) / np.sqrt(2.0)
    grad_tangent = tangent[0] * grad_x + tangent[1] * grad_y
    grad_magnitude = np.hypot(grad_x, grad_y)

    # The literal staircase-edge cells do not possess all four neighbours and
    # are intentionally excluded.  Compare the nearest fully centred band
    # inside the physical half-plane instead of inventing one-sided values at
    # different face locations and combining them as one cell-centred vector.
    lateral_step = max(float(np.max(np.diff(x))), float(np.max(np.diff(y))))
    edge_window = (
        centered_valid
        & (normal_coordinate <= 0.0)
        & (normal_coordinate >= -3.0 * lateral_step)
        & (np.abs(tangent_coordinate) <= edge_window_um * 1e-6)
    )
    if not np.any(edge_window):
        raise RuntimeError("no straight-edge cells in the requested window")
    selected = np.abs(grad_normal[edge_window])
    peak_flat = int(
        np.argmax(np.where(edge_window, np.abs(grad_normal), -1.0))
    )
    peak_index = np.unravel_index(peak_flat, grad_normal.shape)
    metrics = {
        "edge_definition": "TaIrTe4 y<=x; outward normal=(-x+y)/sqrt(2)",
        "gradient_stencil": (
            "strict centered x/y; a sample is masked unless all four "
            "lateral neighbours lie inside TaIrTe4"
        ),
        "edge_comparator_band": (
            "nearest fully centred interior band, -3*max(dx,dy)<=n<=0; "
            "literal staircase-edge cells are excluded"
        ),
        "strict_centered_valid_cell_count": int(np.count_nonzero(centered_valid)),
        "edge_window_um": edge_window_um,
        "edge_cell_count": int(np.count_nonzero(edge_window)),
        "max_abs_edge_normal_gradient_K_m": float(np.max(selected)),
        "p99_abs_edge_normal_gradient_K_m": float(
            np.percentile(selected, 99.0)
        ),
        "max_abs_grad_T_x_K_m": float(np.max(np.abs(grad_x[edge_window]))),
        "max_abs_grad_T_y_K_m": float(np.max(np.abs(grad_y[edge_window]))),
        "max_inplane_gradient_K_m": float(
            np.max(grad_magnitude[edge_window])
        ),
        "max_abs_edge_tangent_gradient_K_m": float(
            np.max(np.abs(grad_tangent[edge_window]))
        ),
        "paper_Fig3G_comparator": (
            "max_abs_grad_T_y_K_m because code y=crystal a; all five "
            "components are retained because edge-normal gradient is not "
            "identical to the paper observable"
        ),
        "peak_edge_gradient_location_m": {
            "x": float(x[peak_index[0]]),
            "y": float(y[peak_index[1]]),
        },
        "Tmax_rise_K": float(np.max(average[mask])),
        "TaIrTe4_area_average_rise_K": measure_weighted_mean(
            average,
            mask,
            np.diff(geometry.x_edges_m)[:, None]
            * np.diff(geometry.y_edges_m)[None, :],
        ),
        "fixed_24um_ROI_area_average_rise_K": measure_weighted_mean(
            average,
            fixed_roi,
            np.diff(geometry.x_edges_m)[:, None]
            * np.diff(geometry.y_edges_m)[None, :],
        ),
        "fixed_ROI_definition": (
            "TaIrTe4 cells with |x|<=12 um and |y|<=12 um; used for "
            "thermal-domain comparisons"
        ),
    }
    return metrics, {
        "temperature_flake_average_K": average,
        "grad_T_x_K_m": grad_x,
        "grad_T_y_K_m": grad_y,
        "grad_T_normal_K_m": grad_normal,
        "grad_T_tangent_K_m": grad_tangent,
        "grad_T_magnitude_K_m": grad_magnitude,
        "edge_window_mask": edge_window,
    }


def load_and_map_q(
    artifact_path: Path,
    result_path: Path,
    geometry: Geometry,
    metal_thermalization: str,
    q_source: str,
    q_attribution: str = "covered-cell-full-power",
    incident_power_W: float = DEFAULT_EXPERIMENTAL_INCIDENT_POWER_W,
) -> tuple[np.ndarray, dict[str, Any]]:
    result = json.loads(result_path.read_text())
    if result.get("status") != "COMPLETED":
        raise RuntimeError("optical case did not complete")
    source_derivation: dict[str, Any] = {
        "method": "stored-array",
        "raw_artifact_modified": False,
    }
    with np.load(artifact_path, allow_pickle=False) as raw:
        x = np.asarray(raw["x_m"], float)
        y = np.asarray(raw["y_m"], float)
        z = np.asarray(raw["z_m"], float)
        if q_source == "TaIrTe4-only":
            # Material attribution is performed below from exact optical-cell
            # / thermal-material overlap.  A centre-point support mask would
            # discard the conformal interface cells that motivated this path.
            q_keys = ["Q_on_W_m3"]
        elif q_source == "TaIrTe4-plus-SiO2":
            q_keys = ["Q_TaIrTe4_only_W_m3", "Q_SiO2_only_W_m3"]
        else:
            q_keys = ["Q_on_W_m3"]
        missing = [key for key in q_keys if key not in raw.files]
        if missing:
            raise RuntimeError(
                f"requested optical sources {missing!r} are absent from artifact"
            )
        source_components = {
            key: np.asarray(raw[key], float)
            for key in q_keys
        }
        if q_source == "TaIrTe4-only":
            formula = (
                "p_m=Q_on[m]*V_opt[m]; distribute complete p_m among exact "
                "thermal-TaIrTe4 overlaps"
                if q_attribution == "covered-cell-full-power"
                else "p_m_to_TaIrTe4=Q_on[m]*|optical cell m intersect "
                "thermal TaIrTe4|; non-overlapping power is not reassigned"
            )
            source_derivation = {
                "method": q_attribution,
                "formula": formula,
                "source_array_key": "Q_on_W_m3",
                "stored_center_support_mask_used_for_mapping": False,
                "raw_artifact_modified": False,
            }
        q = sum(source_components.values())
    optical_geometry = result["pre_run_contract"]["geometry"]
    substrate_contract = optical_geometry.get("substrate_optical_contract", {})
    if (
        substrate_contract.get("model")
        in (
            "lumerical-palik-11um",
            "paper-kitamura-11um",
            "paper-kitamura-palik-nk-11um",
        )
        and q_source not in ("TaIrTe4-only", "TaIrTe4-plus-SiO2")
    ):
        raise RuntimeError(
            "lossy substrate artifact must use --q-source "
            "TaIrTe4-only or TaIrTe4-plus-SiO2; projecting full control-volume "
            "Q would silently move substrate absorption into the flake"
        )
    electrode = optical_geometry.get("electrode_material_contract") or {}
    xx, yy = np.meshgrid(x, y, indexing="ij")
    points = np.column_stack((xx.ravel(), yy.ravel()))

    def optical_xy_mask(vertices_um: list[list[float]]) -> np.ndarray:
        return PolygonPath(np.asarray(vertices_um, float) * 1e-6).contains_points(
            points, radius=1e-15
        ).reshape(xx.shape)

    flake_xy = optical_xy_mask(optical_geometry["flake_vertices_um"])
    electrodes_enabled = bool(
        optical_geometry.get("electrodes_in_optical_model", False)
    )
    if electrodes_enabled:
        metal_xy = optical_xy_mask(
            electrode["top_polygon_simulation_um"]
        ) | optical_xy_mask(electrode["bottom_polygon_simulation_um"])
    else:
        # A deliberately electrode-free optical diagnostic has no metal
        # material contract.  Keep the metal support identically false rather
        # than attempting to infer polygons from the separate electrical
        # weighting geometry.
        metal_xy = np.zeros(xx.shape, dtype=bool)
    at_flake_bottom = np.isclose(z, -THICKNESS_M, rtol=0.0, atol=1e-15)
    at_flake_top = np.isclose(z, 0.0, rtol=0.0, atol=1e-15)
    flake_support = flake_xy[:, :, None] & (
        ((z[None, None, :] >= -THICKNESS_M) | at_flake_bottom[None, None, :])
        & ((z[None, None, :] <= 0.0) | at_flake_top[None, None, :])
    )
    ti_thickness_m = (
        float(electrode["Ti"]["thickness_m"]) if electrodes_enabled else 0.0
    )
    au_thickness_m = (
        float(electrode["Au"]["thickness_m"]) if electrodes_enabled else 0.0
    )
    at_ti_top = np.isclose(z, ti_thickness_m, rtol=0.0, atol=1e-15)
    ti_support = metal_xy[:, :, None] & (
        ((z[None, None, :] >= 0.0) | at_flake_top[None, None, :])
        & (
            (z[None, None, :] <= ti_thickness_m)
            | at_ti_top[None, None, :]
        )
    )
    ti_support &= ~flake_support
    at_au_top = np.isclose(
        z, ti_thickness_m + au_thickness_m, rtol=0.0, atol=1e-15
    )
    au_support = metal_xy[:, :, None] & (
        (z[None, None, :] > ti_thickness_m)
        & ~at_ti_top[None, None, :]
        & (
            (z[None, None, :] <= ti_thickness_m + au_thickness_m)
            | at_au_top[None, None, :]
        )
    )
    metal_support = ti_support | au_support
    assigned_support = flake_support | metal_support
    source_edges = tuple(nodal_control_volume_edges(axis) for axis in (x, y, z))
    target_edges = (geometry.x_edges_m, geometry.y_edges_m, geometry.z_edges_m)
    source_cell_volume = (
        np.diff(source_edges[0])[:, None, None]
        * np.diff(source_edges[1])[None, :, None]
        * np.diff(source_edges[2])[None, None, :]
    )

    def dense_source_power(values: np.ndarray) -> float:
        return float(np.sum(source_cell_volume * np.asarray(values, float)))

    incident_at_unit = float(
        result["run_result"]["normalization"]["incident_power_W_at_1_W_m2"]
    )
    if not np.isfinite(incident_power_W) or incident_power_W <= 0.0:
        raise ValueError("incident power must be finite and positive")
    physical_scale = incident_power_W / incident_at_unit
    full_scaled_q = q * physical_scale
    source_power_by_support = {
        "TaIrTe4_exact_support_W": dense_source_power(full_scaled_q * flake_support),
        "Ti_exact_support_W": dense_source_power(full_scaled_q * ti_support),
        "Au_exact_support_W": dense_source_power(full_scaled_q * au_support),
        "conformal_or_unassigned_W": dense_source_power(
            full_scaled_q * ~assigned_support
        ),
        "full_common_grid_Q_W": dense_source_power(full_scaled_q),
    }
    if q_source == "TaIrTe4-plus-SiO2":
        # The material-resolved optical arrays are already disjoint by exact
        # analytic support.  Report their powers directly instead of folding
        # the oxide contribution into the legacy "unassigned" diagnostic.
        source_power_by_support.update(
            {
                "TaIrTe4_material_resolved_Q_W": dense_source_power(
                    source_components["Q_TaIrTe4_only_W_m3"] * physical_scale
                ),
                "SiO2_material_resolved_Q_W": dense_source_power(
                    source_components["Q_SiO2_only_W_m3"] * physical_scale
                ),
            }
        )
    exact_metal_power = (
        source_power_by_support["Ti_exact_support_W"]
        + source_power_by_support["Au_exact_support_W"]
    )
    full_power = source_power_by_support["full_common_grid_Q_W"]
    if metal_thermalization == "fail-closed":
        if exact_metal_power / max(abs(full_power), np.finfo(float).tiny) > 1e-6:
            raise RuntimeError(
                "Device-A Q contains finite Au/Ti absorption but the expanded "
                "thermal geometry has no published hidden metal overlap or "
                "metal/TaIrTe4 interface contract; choose the explicitly named "
                "isolated-lower-bound or add explicit metal thermal cells and "
                "a documented interface"
            )
        scaled_q = full_scaled_q
    elif metal_thermalization == "isolated-lower-bound":
        # Exact metal absorption remains reported but is not injected into the
        # flake-only thermal model.  No remaining Q is re-normalized.
        scaled_q = full_scaled_q * ~metal_support
    elif metal_thermalization == "perfect-to-flake-upper-bound":
        raise RuntimeError(
            "perfect-to-flake-upper-bound required nearest-cell relocation, "
            "which is forbidden by the material-overlap contract; add explicit "
            "metal thermal cells and a documented metal/TaIrTe4 interface "
            "instead of forcing zero-overlap power into the flake"
        )
    else:
        raise ValueError(f"unknown metal thermalization scenario {metal_thermalization}")

    if q_attribution == "intersection-density":
        if q_source != "TaIrTe4-only":
            raise RuntimeError(
                "intersection-density currently requires TaIrTe4-only Q"
            )
        mapped, flake_source_overlap, intersection_audit = (
            apply_material_intersection_density_separable(
                source_density=scaled_q,
                source_edges_m=source_edges,
                target_edges_m=target_edges,
                target_material_support_mask=geometry.flake_mask,
            )
        )
        flake_source_active = flake_source_overlap > 0.0
        flake_overlap_fraction = np.divide(
            flake_source_overlap,
            source_cell_volume,
            out=np.zeros_like(flake_source_overlap),
            where=source_cell_volume > 0.0,
        )
        p_source = float(intersection_audit["material_attributed_source_power_W"])
        p_target = float(intersection_audit["target_integrated_power_W"])
        full_nonmetal_source = dense_source_power(scaled_q)
        zero_overlap_unattributed = dense_source_power(
            np.where(flake_source_active, 0.0, scaled_q)
        )
        partial_unattributed = full_nonmetal_source - p_source - zero_overlap_unattributed
        target_volume = (
            np.diff(target_edges[0])[:, None, None]
            * np.diff(target_edges[1])[None, :, None]
            * np.diff(target_edges[2])[None, None, :]
        )
        outside_power = float(
            np.sum(target_volume[~geometry.flake_mask] * mapped[~geometry.flake_mask])
        )
        return mapped, {
            "optical_artifact_path": str(artifact_path.resolve()),
            "optical_artifact_sha256": sha256(artifact_path),
            "optical_result_path": str(result_path.resolve()),
            "optical_result_sha256": sha256(result_path),
            "experimental_incident_power_W": incident_power_W,
            "selected_Q_source": q_source,
            "selected_Q_artifact_keys": q_keys,
            "selected_Q_attribution": q_attribution,
            "selected_Q_derivation": source_derivation,
            "substrate_optical_contract": substrate_contract,
            "unit_central_intensity_incident_power_W": incident_at_unit,
            "physical_incident_power_scale": physical_scale,
            "metal_thermalization_scenario": metal_thermalization,
            "source_power_by_optical_material_support_W": source_power_by_support,
            "exact_metal_power_excluded_from_modeled_source_W": (
                exact_metal_power
                if metal_thermalization == "isolated-lower-bound"
                else 0.0
            ),
            "modeled_source_fraction_of_full_common_grid_Q": p_source / full_power,
            "P_Q_source_W": p_source,
            "P_Q_target_W": p_target,
            "material_resolved_source_target_power_W": {
                "TaIrTe4_source_W": p_source,
                "TaIrTe4_target_W": p_target,
                "SiO2_source_W": 0.0,
                "SiO2_target_W": 0.0,
            },
            "mapping_relative_power_error": intersection_audit[
                "relative_power_error"
            ],
            "material_resolved_support_leakage_W": {
                "TaIrTe4_zero_overlap_unattributed_W": zero_overlap_unattributed,
                "TaIrTe4_partial_cell_nonintersection_unattributed_W": (
                    partial_unattributed
                ),
                "TaIrTe4_total_nonintersection_unattributed_W": (
                    full_nonmetal_source - p_source
                ),
                "TaIrTe4_after_intersection_mapping_outside_TaIrTe4_W": (
                    outside_power
                ),
                "interpretation": (
                    "Q times literal optical-cell/discrete-TaIrTe4 "
                    "intersection volume only; neither zero-overlap nor "
                    "partial cut-cell remainder is forced into TaIrTe4"
                ),
            },
            "TaIrTe4_source_material_overlap": {
                "material_domain": (
                    "union of thermal FVM cells assigned material_id=3"
                ),
                "covered_source_cell_count": int(
                    np.count_nonzero(flake_source_active)
                ),
                "zero_overlap_source_cell_count": int(
                    flake_source_active.size - np.count_nonzero(flake_source_active)
                ),
                "covered_overlap_fraction_minimum": float(
                    np.min(flake_overlap_fraction[flake_source_active])
                ),
                "covered_overlap_fraction_maximum": float(
                    np.max(flake_overlap_fraction[flake_source_active])
                ),
                "full_cell_power_is_preserved_for_every_covered_source_cell": False,
            },
            "mapped_power_outside_flake_before_final_support_W": None,
            "mapped_power_outside_flake_before_final_support_fraction": None,
            "mapped_power_outside_flake_W": outside_power,
            "legacy_outside_flake_metric_interpretation": (
                "not applicable: intersection deposition is material-supported "
                "by construction"
            ),
            "mapping_operations": (
                "separable exact Cartesian optical-cell/TaIrTe4-intersection "
                "density deposition; no 3-D Kronecker materialization, "
                "nearest-cell projection, clipping, smoothing, gain, global "
                "rescaling, or tiling"
            ),
        }

    base_remap = build_conservative_embedding_remap(
        source_edges_m=source_edges,
        target_edges_m=target_edges,
    )
    if q_attribution == "covered-cell-full-power":
        flake_remap = build_material_overlap_remap(
            source_edges_m=source_edges,
            target_edges_m=target_edges,
            target_material_support_mask=geometry.flake_mask,
        )
    else:
        raise ValueError(f"unknown Q attribution scenario {q_attribution}")
    flake_source_overlap = np.asarray(
        flake_remap.source_material_overlap_m3, float
    )
    flake_source_active = flake_source_overlap > 0.0
    source_cell_volume = base_remap.source_volume_m3
    flake_overlap_fraction = np.divide(
        flake_source_overlap,
        source_cell_volume,
        out=np.zeros_like(flake_source_overlap),
        where=source_cell_volume > 0.0,
    )
    material_support_leakage: dict[str, float | str] = {}
    if q_source == "TaIrTe4-plus-SiO2":
        sio2_target = geometry.material_id == 2
        if not np.any(sio2_target):
            raise RuntimeError("thermal geometry has no SiO2 target cells")
        sio2_remap = build_material_overlap_remap(
            source_edges_m=source_edges,
            target_edges_m=target_edges,
            target_material_support_mask=sio2_target,
        )
        sio2_source_overlap = np.asarray(
            sio2_remap.source_material_overlap_m3, float
        )
        sio2_source_active = sio2_source_overlap > 0.0
        flake_source_raw = (
            source_components["Q_TaIrTe4_only_W_m3"] * physical_scale
        )
        sio2_source_raw = (
            source_components["Q_SiO2_only_W_m3"] * physical_scale
        )
        flake_source = np.where(flake_source_active, flake_source_raw, 0.0)
        sio2_source = np.where(sio2_source_active, sio2_source_raw, 0.0)
        unprojected_flake = base_remap.apply(flake_source)
        unprojected_sio2 = base_remap.apply(sio2_source)
        material_support_leakage = {
            "TaIrTe4_before_overlap_mapping_outside_TaIrTe4_W": float(
                np.sum(
                    base_remap.target_volume_m3[~geometry.flake_mask]
                    * unprojected_flake[~geometry.flake_mask]
                )
            ),
            "SiO2_before_overlap_mapping_outside_SiO2_W": float(
                np.sum(
                    base_remap.target_volume_m3[~sio2_target]
                    * unprojected_sio2[~sio2_target]
                )
            ),
            "TaIrTe4_zero_overlap_unattributed_W": base_remap.power_source(
                np.where(flake_source_active, 0.0, flake_source_raw)
            ),
            "SiO2_zero_overlap_unattributed_W": base_remap.power_source(
                np.where(sio2_source_active, 0.0, sio2_source_raw)
            ),
        }
        mapped_flake = flake_remap.apply(flake_source)
        mapped_sio2 = sio2_remap.apply(sio2_source)
        mapped = mapped_flake + mapped_sio2
        p_source_flake = flake_remap.power_source(flake_source)
        p_source_sio2 = sio2_remap.power_source(sio2_source)
        p_source = p_source_flake + p_source_sio2
        target_volume = base_remap.target_volume_m3
        p_target_flake = flake_remap.power_target(mapped_flake)
        p_target_sio2 = sio2_remap.power_target(mapped_sio2)
        p_target = p_target_flake + p_target_sio2
        material_target_power = {
            "TaIrTe4_source_W": p_source_flake,
            "TaIrTe4_target_W": p_target_flake,
            "SiO2_source_W": p_source_sio2,
            "SiO2_target_W": p_target_sio2,
        }
        material_support_leakage.update(
            {
                "TaIrTe4_after_overlap_mapping_outside_TaIrTe4_W": float(
                    np.sum(
                        target_volume[~geometry.flake_mask]
                        * mapped_flake[~geometry.flake_mask]
                    )
                ),
                "SiO2_after_overlap_mapping_outside_SiO2_W": float(
                    np.sum(
                        target_volume[~sio2_target]
                        * mapped_sio2[~sio2_target]
                    )
                ),
                "combined_after_projection_outside_material_union_W": float(
                    np.sum(
                        target_volume[
                            ~(geometry.flake_mask | sio2_target)
                        ]
                        * mapped[
                            ~(geometry.flake_mask | sio2_target)
                        ]
                    )
                ),
                "interpretation": (
                    "each source-cell power is distributed only through its "
                    "actual overlap with the corresponding discrete FVM "
                    "material volume; zero-overlap power is reported rather "
                    "than moved to a nearest cell"
                ),
            }
        )
        mapping_description = (
            "two independent exact material-overlap power maps: TaIrTe4 Q "
            "to the discrete TaIrTe4 FVM volume and SiO2 Q to the discrete "
            "SiO2 FVM volume"
        )
        outside_power_before = None
    else:
        material_source = (
            np.where(flake_source_active, scaled_q, 0.0)
            if q_attribution == "covered-cell-full-power"
            else scaled_q
        )
        unattributed_source = np.where(flake_source_active, 0.0, scaled_q)
        unprojected = base_remap.apply(material_source)
        outside_power_before = float(
            np.sum(
                base_remap.target_volume_m3[~geometry.flake_mask]
                * unprojected[~geometry.flake_mask]
            )
        )
        mapped = flake_remap.apply(material_source)
        p_source = (
            flake_remap.power_source(material_source)
            if q_attribution == "covered-cell-full-power"
            else flake_remap.material_attributed_source_power(material_source)
        )
        target_volume = flake_remap.target_volume_m3
        p_target = flake_remap.power_target(mapped)
        material_target_power = {
            "TaIrTe4_source_W": p_source,
            "TaIrTe4_target_W": p_target,
            "SiO2_source_W": 0.0,
            "SiO2_target_W": 0.0,
        }
        material_support_leakage = {
            "TaIrTe4_before_overlap_mapping_outside_TaIrTe4_W": (
                outside_power_before
            ),
            "TaIrTe4_zero_overlap_unattributed_W": (
                base_remap.power_source(unattributed_source)
            ),
            "TaIrTe4_partial_cell_nonintersection_unattributed_W": (
                0.0
                if q_attribution == "covered-cell-full-power"
                else base_remap.power_source(material_source) - p_source
            ),
            "TaIrTe4_after_overlap_mapping_outside_TaIrTe4_W": float(
                np.sum(
                    target_volume[~geometry.flake_mask]
                    * mapped[~geometry.flake_mask]
                )
            ),
            "interpretation": (
                "zero-overlap optical power is not relocated; "
                + (
                    "every covered source cell keeps its complete cell power"
                    if q_attribution == "covered-cell-full-power"
                    else "only literal optical-cell/TaIrTe4-intersection power "
                    "is attributed; the remaining cut-cell fraction is not "
                    "forced into TaIrTe4"
                )
            ),
        }
        mapping_description = (
            "one optical-cell/thermal-TaIrTe4 map using the named "
            f"{q_attribution} attribution contract"
        )
    outside_power = float(
        np.sum(target_volume[~geometry.flake_mask] * mapped[~geometry.flake_mask])
    )
    legacy_outside_flake_before = outside_power_before
    legacy_outside_flake_after = (
        None if q_source == "TaIrTe4-plus-SiO2" else outside_power
    )
    return mapped, {
        "optical_artifact_path": str(artifact_path.resolve()),
        "optical_artifact_sha256": sha256(artifact_path),
        "optical_result_path": str(result_path.resolve()),
        "optical_result_sha256": sha256(result_path),
        "experimental_incident_power_W": incident_power_W,
        "selected_Q_source": q_source,
        "selected_Q_artifact_keys": q_keys,
        "selected_Q_attribution": q_attribution,
        "selected_Q_derivation": source_derivation,
        "substrate_optical_contract": substrate_contract,
        "unit_central_intensity_incident_power_W": incident_at_unit,
        "physical_incident_power_scale": physical_scale,
        "metal_thermalization_scenario": metal_thermalization,
        "source_power_by_optical_material_support_W": source_power_by_support,
        "exact_metal_power_excluded_from_modeled_source_W": (
            exact_metal_power
            if metal_thermalization == "isolated-lower-bound"
            else 0.0
        ),
        "modeled_source_fraction_of_full_common_grid_Q": p_source / full_power,
        "P_Q_source_W": p_source,
        "P_Q_target_W": p_target,
        "material_resolved_source_target_power_W": material_target_power,
        "mapping_relative_power_error": abs(p_target - p_source) / abs(p_source),
        "material_resolved_support_leakage_W": material_support_leakage,
        "TaIrTe4_source_material_overlap": {
            "material_domain": (
                "union of thermal FVM cells explicitly assigned material_id=3; "
                "this keeps source and conductivity geometry identical"
            ),
            "covered_source_cell_count": int(np.count_nonzero(flake_source_active)),
            "zero_overlap_source_cell_count": int(
                flake_source_active.size - np.count_nonzero(flake_source_active)
            ),
            "covered_overlap_fraction_minimum": (
                float(np.min(flake_overlap_fraction[flake_source_active]))
                if np.any(flake_source_active)
                else None
            ),
            "covered_overlap_fraction_maximum": (
                float(np.max(flake_overlap_fraction[flake_source_active]))
                if np.any(flake_source_active)
                else None
            ),
            "full_cell_power_is_preserved_for_every_covered_source_cell": (
                q_attribution == "covered-cell-full-power"
            ),
        },
        "mapped_power_outside_flake_before_final_support_W": (
            legacy_outside_flake_before
        ),
        "mapped_power_outside_flake_before_final_support_fraction": (
            None
            if legacy_outside_flake_before is None
            else legacy_outside_flake_before / p_source
        ),
        "mapped_power_outside_flake_W": legacy_outside_flake_after,
        "legacy_outside_flake_metric_interpretation": (
            "not applicable to a TaIrTe4-plus-SiO2 source because valid SiO2 "
            "heating is outside the flake; use material_resolved_support_leakage_W"
            if q_source == "TaIrTe4-plus-SiO2"
            else "legacy single-flake-support diagnostic"
        ),
        "mapping_operations": (
            f"{mapping_description}; no nearest-cell projection, coordinate-"
            "axis ordering, clipping, smoothing, gain, global rescaling, or "
            "tiling; zero-overlap power is retained only as an attribution "
            "diagnostic; metal handling is "
            f"the explicitly named {metal_thermalization} scenario"
        ),
    }


def pte_current(
    temperature_K: np.ndarray,
    geometry: Geometry,
    grad_psi_x: np.ndarray,
    grad_psi_y: np.ndarray,
) -> tuple[float, dict[str, np.ndarray]]:
    x = 0.5 * (geometry.x_edges_m[:-1] + geometry.x_edges_m[1:])
    y = 0.5 * (geometry.y_edges_m[:-1] + geometry.y_edges_m[1:])
    dz = np.diff(geometry.z_edges_m)
    flake_z = np.flatnonzero(np.any(geometry.flake_mask, axis=(0, 1)))
    thickness = float(np.sum(dz[flake_z]))
    average = np.sum(
        temperature_K[:, :, flake_z] * dz[flake_z][None, None, :], axis=2
    ) / thickness
    mask = np.any(geometry.flake_mask, axis=2)
    grad_tx, grad_ty = cell_gradient(average, mask, x, y)
    local_x = -SIGMA_LAB_S_M[0] * SEEBECK_LAB_V_K[0] * grad_tx
    local_y = -SIGMA_LAB_S_M[1] * SEEBECK_LAB_V_K[1] * grad_ty
    area = np.diff(geometry.x_edges_m)[:, None] * np.diff(geometry.y_edges_m)[None, :]
    density = (local_x * grad_psi_x + local_y * grad_psi_y) * thickness
    sheet_current = float(np.sum(density[mask] * area[mask]))

    local_x_3d = np.zeros_like(temperature_K)
    local_y_3d = np.zeros_like(temperature_K)
    integrand_3d = np.zeros_like(temperature_K)
    volume_current = 0.0
    for k in flake_z:
        gx, gy = cell_gradient(temperature_K[:, :, k], mask, x, y)
        jx = -SIGMA_LAB_S_M[0] * SEEBECK_LAB_V_K[0] * gx
        jy = -SIGMA_LAB_S_M[1] * SEEBECK_LAB_V_K[1] * gy
        integrand = jx * grad_psi_x + jy * grad_psi_y
        local_x_3d[:, :, k] = jx
        local_y_3d[:, :, k] = jy
        integrand_3d[:, :, k] = integrand
        volume_current += float(
            np.sum(integrand[mask] * area[mask] * dz[k])
        )
    equivalence = abs(volume_current - sheet_current) / max(
        abs(volume_current), abs(sheet_current), np.finfo(float).tiny
    )
    return volume_current, {
        "temperature_flake_average_K": average,
        "grad_T_x_K_m": grad_tx,
        "grad_T_y_K_m": grad_ty,
        "local_J_x_A_m2": local_x,
        "local_J_y_A_m2": local_y,
        "shockley_ramo_integrand_A_m2": density,
        "local_J_x_A_m2_3d": local_x_3d,
        "local_J_y_A_m2_3d": local_y_3d,
        "shockley_ramo_integrand_A_m3_3d": integrand_3d,
        "PTE_current_volume_integral_A": np.asarray([volume_current]),
        "PTE_current_thickness_integrated_area_A": np.asarray([sheet_current]),
        "PTE_volume_area_equivalence_relative_error": np.asarray([equivalence]),
    }


def pte_current_strict_centered(
    temperature_K: np.ndarray,
    geometry: Geometry,
    weighting_potential: np.ndarray,
) -> tuple[float, dict[str, np.ndarray | float | int | str]]:
    """Cell-centred diagnostic with a common four-neighbour validity mask.

    This implements the user's requested strict masking rule literally: a
    cell contributes only when all +/-x and +/-y neighbours are TaIrTe4 for
    both the temperature and weighting-potential gradients.  It is a useful
    stencil audit, but it removes the boundary-adjacent physical volume and is
    therefore not silently promoted as the production terminal current.
    """

    x = 0.5 * (geometry.x_edges_m[:-1] + geometry.x_edges_m[1:])
    y = 0.5 * (geometry.y_edges_m[:-1] + geometry.y_edges_m[1:])
    dx = np.diff(geometry.x_edges_m)
    dy = np.diff(geometry.y_edges_m)
    dz = np.diff(geometry.z_edges_m)
    mask = np.any(geometry.flake_mask, axis=2)
    flake_z = np.flatnonzero(np.any(geometry.flake_mask, axis=(0, 1)))
    grad_psi_x, grad_psi_y, valid = strict_centered_cell_gradient(
        weighting_potential, mask, x, y
    )
    area = dx[:, None] * dy[None, :]
    cell_contribution = np.zeros_like(temperature_K)
    current = 0.0
    for k in flake_z:
        grad_tx, grad_ty, valid_t = strict_centered_cell_gradient(
            temperature_K[:, :, k], mask, x, y
        )
        common = valid & valid_t
        integrand = (
            -SIGMA_LAB_S_M[0]
            * SEEBECK_LAB_V_K[0]
            * grad_tx
            * grad_psi_x
            - SIGMA_LAB_S_M[1]
            * SEEBECK_LAB_V_K[1]
            * grad_ty
            * grad_psi_y
        )
        contribution = np.zeros_like(integrand)
        contribution[common] = integrand[common] * area[common] * dz[k]
        cell_contribution[:, :, k] = contribution
        current += float(np.sum(contribution))
    return current, {
        "current_A": current,
        "cell_contribution_A": cell_contribution,
        "valid_xy_mask": valid,
        "valid_xy_cell_count": int(np.count_nonzero(valid)),
        "masked_flake_xy_cell_count": int(np.count_nonzero(mask & ~valid)),
        "contract": (
            "strict cell-centred +/-x,+/-y stencil; any missing neighbour "
            "masks the entire cell contribution"
        ),
        "production_status": "DIAGNOSTIC_ONLY_BOUNDARY_VOLUME_REMOVED",
    }


def pte_current_internal_face_bilinear(
    temperature_K: np.ndarray,
    geometry: Geometry,
    weighting_potential: np.ndarray,
) -> tuple[float, dict[str, np.ndarray | float | int | str]]:
    """Symmetric internal-face discretization of the PTE bilinear form.

    On every TaIrTe4--TaIrTe4 face this evaluates the temperature and
    weighting-potential differences at exactly the same physical face and
    multiplies by that face's dual volume.  This removes the legacy operation
    of combining x/y one-sided differences evaluated at different locations.

    Exterior half control volumes are intentionally not invented here.  A
    production promotion still requires an explicit thermal/electrical
    boundary-face quadrature contract, especially at the metal contacts.
    """

    x = 0.5 * (geometry.x_edges_m[:-1] + geometry.x_edges_m[1:])
    y = 0.5 * (geometry.y_edges_m[:-1] + geometry.y_edges_m[1:])
    dx = np.diff(geometry.x_edges_m)
    dy = np.diff(geometry.y_edges_m)
    dz = np.diff(geometry.z_edges_m)
    mask = np.any(geometry.flake_mask, axis=2)
    flake_z = np.flatnonzero(np.any(geometry.flake_mask, axis=(0, 1)))
    connected_x = mask[:-1, :] & mask[1:, :]
    connected_y = mask[:, :-1] & mask[:, 1:]
    dpsi_x = weighting_potential[1:, :] - weighting_potential[:-1, :]
    dpsi_y = weighting_potential[:, 1:] - weighting_potential[:, :-1]
    distance_x = x[1:] - x[:-1]
    distance_y = y[1:] - y[:-1]
    face_x_A = np.zeros((mask.shape[0] - 1, mask.shape[1], temperature_K.shape[2]))
    face_y_A = np.zeros((mask.shape[0], mask.shape[1] - 1, temperature_K.shape[2]))
    current_x = 0.0
    current_y = 0.0
    for k in flake_z:
        temperature = temperature_K[:, :, k]
        dtemp_x = temperature[1:, :] - temperature[:-1, :]
        dtemp_y = temperature[:, 1:] - temperature[:, :-1]
        contribution_x = (
            -SIGMA_LAB_S_M[0]
            * SEEBECK_LAB_V_K[0]
            * dtemp_x
            * dpsi_x
            / distance_x[:, None]
            * dy[None, :]
            * dz[k]
        )
        contribution_y = (
            -SIGMA_LAB_S_M[1]
            * SEEBECK_LAB_V_K[1]
            * dtemp_y
            * dpsi_y
            / distance_y[None, :]
            * dx[:, None]
            * dz[k]
        )
        face_x_A[:, :, k][connected_x] = contribution_x[connected_x]
        face_y_A[:, :, k][connected_y] = contribution_y[connected_y]
        current_x += float(np.sum(contribution_x[connected_x]))
        current_y += float(np.sum(contribution_y[connected_y]))
    current = current_x + current_y
    return current, {
        "current_A": current,
        "current_x_faces_A": current_x,
        "current_y_faces_A": current_y,
        "face_x_contribution_A": face_x_A,
        "face_y_contribution_A": face_y_A,
        "connected_x_face_count": int(np.count_nonzero(connected_x)),
        "connected_y_face_count": int(np.count_nonzero(connected_y)),
        "contract": (
            "symmetric TaIrTe4--TaIrTe4 internal-face bilinear form; T and "
            "psi differences share the same face and dual volume"
        ),
        "exterior_boundary_half_control_volumes_included": False,
        "production_status": (
            "DIAGNOSTIC_ONLY_PENDING_EXPLICIT_CONTACT_BOUNDARY_FACE_QUADRATURE"
        ),
    }


def load_optical_coordinate_frame(
    optical_case_dir: Path,
) -> tuple[Path, dict[str, Any], float, float]:
    """Read the coordinate frame frozen by the actual optical case.

    Device-A is translated to center the union of its metal and finite source
    aperture.  Consequently, changing the optical domain or source aperture
    changes the simulation-frame coordinates even though every relative
    physical coordinate is preserved.  Thermal post-processing must reuse
    those exact optical values rather than silently falling back to 60/50 um.
    """
    result_path = optical_case_dir / "case_result.json"
    if not result_path.is_file():
        raise FileNotFoundError(f"optical case result is missing: {result_path}")
    result = json.loads(result_path.read_text())
    try:
        domain_um = float(result["domain_um"])
        source_span_um = float(result["source_span_um"])
    except (KeyError, TypeError, ValueError) as exc:
        raise ValueError(
            "optical case_result.json must explicitly record domain_um and "
            "source_span_um so the thermal geometry uses the identical "
            "translated Device-A coordinate frame"
        ) from exc
    if not np.isfinite(domain_um) or domain_um <= 0.0:
        raise ValueError("optical domain_um must be finite and positive")
    if not np.isfinite(source_span_um) or source_span_um <= 0.0:
        raise ValueError("optical source_span_um must be finite and positive")
    return result_path, result, domain_um, source_span_um


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--optical-case-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--thermal-domain-um", type=float, default=48.0)
    parser.add_argument("--si-depth-um", type=float, default=20.0)
    parser.add_argument("--core-step-nm", type=float, default=200.0)
    parser.add_argument("--flake-dz-nm", type=float, default=26.0)
    parser.add_argument(
        "--tairte4-sio2-interface-scenario",
        choices=("thermally-grown", "evaporated"),
        default="thermally-grown",
        help=(
            "named paper interface-G scenario; changes only internal "
            "TaIrTe4/SiO2 z-face resistance"
        ),
    )
    parser.add_argument(
        "--incident-power-uw",
        type=float,
        default=285.0,
        help=(
            "time-averaged incident power; use 284.40 for the exact SI "
            "Device-A 11-um measurement rather than the rounded 285-uW caption"
        ),
    )
    parser.add_argument(
        "--mapping-only",
        action="store_true",
        help=(
            "build and audit the optical-to-thermal material-overlap map, "
            "then stop before thermal, weighting-potential, or PTE solves"
        ),
    )
    parser.add_argument(
        "--geometry-contract-json",
        type=Path,
        default=None,
        help="frozen Device-A Figure-2/3 digitization contract",
    )
    parser.add_argument(
        "--geometry",
        choices=("device-a-polygon", "straight-45-edge"),
        default="device-a-polygon",
    )
    parser.add_argument(
        "--thermal-model",
        choices=("expanded", "paper-reduced"),
        default="expanded",
    )
    parser.add_argument(
        "--metal-thermalization",
        choices=(
            "fail-closed",
            "isolated-lower-bound",
            "perfect-to-flake-upper-bound",
        ),
        default="fail-closed",
        help=(
            "named diagnostic bound for optical Au/Ti absorption; neither "
            "bound is a published finite metal-interface model; the legacy "
            "perfect-to-flake option now fails closed because nearest-cell "
            "power relocation is forbidden"
        ),
    )
    parser.add_argument(
        "--q-source",
        choices=(
            "full-control-volume",
            "TaIrTe4-only",
            "TaIrTe4-plus-SiO2",
        ),
        default="full-control-volume",
        help=(
            "select the raw full optical control-volume Q, TaIrTe4 power "
            "attributed by optical-cell/thermal-material overlap, or "
            "independently mapped TaIrTe4-plus-SiO2 sources; lossy Palik "
            "substrates forbid the unpartitioned full-control-volume source"
        ),
    )
    parser.add_argument(
        "--q-attribution",
        choices=("covered-cell-full-power", "intersection-density"),
        default="covered-cell-full-power",
        help=(
            "for TaIrTe4-only Q, either preserve the complete power of every "
            "source cell having any TaIrTe4 overlap (legacy) or attribute only "
            "Q times the literal optical-cell/TaIrTe4 intersection volume"
        ),
    )
    args = parser.parse_args()
    if (
        args.q_source == "TaIrTe4-plus-SiO2"
        and args.q_attribution != "covered-cell-full-power"
    ):
        parser.error(
            "intersection-density is currently certified only for the "
            "TaIrTe4-only source; do not mix material attribution contracts"
        )
    args.output_dir.mkdir(parents=True, exist_ok=False)
    selected_tairte4_sio2_G = {
        "thermally-grown": G_TAIRTE4_THERMALLY_GROWN_SIO2_W_M2K,
        "evaporated": G_TAIRTE4_EVAPORATED_SIO2_W_M2K,
    }[args.tairte4_sio2_interface_scenario]
    (
        optical_result_path,
        optical_case_result,
        optical_domain_um,
        optical_source_span_um,
    ) = load_optical_coordinate_frame(args.optical_case_dir)
    global FLAKE_VERTICES_UM, TOP_CONTACT_SEGMENT_UM, BOTTOM_CONTACT_SEGMENT_UM
    digitized_contract = None
    if args.geometry_contract_json is not None:
        optical_digitized = optical_case_result.get("pre_run_contract", {}).get(
            "geometry", {}
        ).get("digitized_device_a_contract")
        if not isinstance(optical_digitized, dict):
            raise ValueError(
                "optical case_result.json does not contain the realized "
                "digitized Device-A coordinate contract"
            )
        requested_geometry_path = args.geometry_contract_json.resolve()
        optical_geometry_path = Path(str(optical_digitized.get("path", ""))).resolve()
        if optical_geometry_path != requested_geometry_path:
            raise ValueError(
                "thermal geometry contract differs from the geometry used by "
                f"the optical solve: {requested_geometry_path} != "
                f"{optical_geometry_path}"
            )
        payload = json.loads(requested_geometry_path.read_text())
        shift = np.asarray(
            optical_digitized["simulation_origin_shift_um"], float
        )
        realized_flake = np.asarray(
            optical_digitized["flake_vertices_simulation_um"], float
        )
        reconstructed_flake = (
            np.asarray(payload["flake_vertices_code_um"], float) + shift
        )
        if not np.allclose(
            realized_flake, reconstructed_flake, rtol=0.0, atol=1.0e-9
        ):
            raise ValueError(
                "realized optical flake coordinates do not equal the frozen "
                "digitized polygon plus the recorded optical origin shift"
            )
        digitized_contract = dict(optical_digitized)
        digitized_contract["payload"] = payload
        digitized_contract[
            "thermal_geometry_loaded_from_actual_optical_case_result"
        ] = True
        digitized_contract["optical_domain_um"] = optical_domain_um
        digitized_contract["optical_source_span_um"] = optical_source_span_um
        FLAKE_VERTICES_UM = np.asarray(
            digitized_contract["flake_vertices_simulation_um"], float
        )
        TOP_CONTACT_SEGMENT_UM = np.asarray(
            payload["top_electrical_contact_segment_code_um"], float
        ) + shift
        BOTTOM_CONTACT_SEGMENT_UM = np.asarray(
            payload["bottom_electrical_contact_segment_code_um"], float
        ) + shift
        if np.max(np.abs(FLAKE_VERTICES_UM)) >= 0.5 * args.thermal_domain_um:
            raise ValueError(
                "thermal domain does not contain the frozen translated "
                "Device-A flake polygon"
            )
    if args.geometry == "straight-45-edge":
        outer_um = 0.5 * args.thermal_domain_um + 1.0
        FLAKE_VERTICES_UM = np.asarray(
            [
                [-outer_um, -outer_um],
                [outer_um, -outer_um],
                [outer_um, outer_um],
            ],
            dtype=float,
        )
    print("[thermal] building explicit 3D geometry", flush=True)
    geometry = build_geometry(
        domain_m=args.thermal_domain_um * 1e-6,
        si_depth_m=args.si_depth_um * 1e-6,
        core_step_m=args.core_step_nm * 1e-9,
        flake_dz_m=args.flake_dz_nm * 1e-9,
        tairte4_sio2_G_W_m2K=selected_tairte4_sio2_G,
    )
    print(
        f"[thermal] grid shape={geometry.material_id.shape}, "
        f"cells={geometry.material_id.size}",
        flush=True,
    )
    print("[thermal] loading and conservatively remapping optical Q", flush=True)
    q, mapping = load_and_map_q(
        args.optical_case_dir / "finite_q_on_artifact.npz",
        args.optical_case_dir / "case_result.json",
        geometry,
        args.metal_thermalization,
        args.q_source,
        args.q_attribution,
        args.incident_power_uw * 1.0e-6,
    )
    print("[thermal] optical Q remap complete", flush=True)
    if args.mapping_only:
        thermal_volume_m3 = (
            np.diff(geometry.x_edges_m)[:, None, None]
            * np.diff(geometry.y_edges_m)[None, :, None]
            * np.diff(geometry.z_edges_m)[None, None, :]
        )
        outside_selected_material_W = float(
            np.sum(
                thermal_volume_m3[~geometry.flake_mask]
                * q[~geometry.flake_mask]
            )
        )
        mapping_gates = {
            "source_target_power_error_lt_1e_minus_12": (
                mapping["mapping_relative_power_error"] < 1.0e-12
            ),
            "mapped_Q_is_finite": bool(np.all(np.isfinite(q))),
            "mapped_Q_has_no_negative_cells": bool(np.count_nonzero(q < 0.0) == 0),
            "TaIrTe4_only_power_outside_TaIrTe4_is_zero": (
                args.q_source != "TaIrTe4-only"
                or abs(outside_selected_material_W)
                <= np.finfo(float).tiny
            ),
        }
        mapping_only = {
            "status": (
                "VALIDATED_MATERIAL_OVERLAP_REMAP_EXECUTION"
                if all(mapping_gates.values())
                else "FAILED_MATERIAL_OVERLAP_REMAP_EXECUTION"
            ),
            "scope": (
                "optical-to-thermal source mapping only; no thermal solve, "
                "weighting potential, PTE current, adjoint, or optimization"
            ),
            "mapping": mapping,
            "thermal_grid_shape": list(geometry.material_id.shape),
            "thermal_cell_count": int(geometry.material_id.size),
            "mapped_Q_shape": list(q.shape),
            "mapped_Q_nonzero_cell_count": int(np.count_nonzero(q)),
            "mapped_Q_min_W_m3": float(np.min(q)),
            "mapped_Q_max_W_m3": float(np.max(q)),
            "mapped_Q_finite": bool(np.all(np.isfinite(q))),
            "mapped_Q_negative_cell_count": int(np.count_nonzero(q < 0.0)),
            "mapped_power_outside_TaIrTe4_W": outside_selected_material_W,
            "gates": mapping_gates,
            "heat_run": False,
            "weighting_potential_run": False,
            "PTE_run": False,
            "adjoint_run": False,
            "optimization_run": False,
        }
        (args.output_dir / "material_overlap_mapping_summary.json").write_text(
            json.dumps(jsonable(mapping_only), indent=2) + "\n"
        )
        np.savez_compressed(
            args.output_dir / "material_overlap_mapped_q.npz",
            x_edges_m=geometry.x_edges_m,
            y_edges_m=geometry.y_edges_m,
            z_edges_m=geometry.z_edges_m,
            Q_W_m3=q,
            TaIrTe4_support_mask=geometry.flake_mask,
        )
        print(json.dumps(jsonable(mapping_only), indent=2))
        return 0
    expanded_geometry = geometry
    if args.thermal_model == "paper-reduced":
        geometry, q = reduced_flake_geometry(geometry, q)
        system = assemble_steady_diagonal_kappa(
            x_edges_m=geometry.x_edges_m,
            y_edges_m=geometry.y_edges_m,
            z_edges_m=geometry.z_edges_m,
            kappa_W_mK=geometry.kappa_W_mK,
            dirichlet_temperature_K={},
            interface_resistance_m2K_W=geometry.interface_resistance_m2K_W,
            active_mask=geometry.flake_mask,
            surface_robin_heat_transfer_W_m2K={
                "z_min": selected_tairte4_sio2_G,
                "z_max": G_TAIRTE4_AIR_W_M2K,
            },
            surface_robin_temperature_K={"z_min": 0.0, "z_max": 0.0},
        )
    else:
        print("[thermal] assembling expanded FVM operator", flush=True)
        system = assemble_steady_diagonal_kappa(
            x_edges_m=geometry.x_edges_m,
            y_edges_m=geometry.y_edges_m,
            z_edges_m=geometry.z_edges_m,
            kappa_W_mK=geometry.kappa_W_mK,
            dirichlet_temperature_K={
                "x_min": 0.0,
                "x_max": 0.0,
                "y_min": 0.0,
                "y_max": 0.0,
                "z_min": 0.0,
            },
            interface_resistance_m2K_W=geometry.interface_resistance_m2K_W,
            active_mask=np.ones(geometry.material_id.shape, bool),
            exposed_heat_transfer_W_m2K=H_EXPOSED_W_M2K,
            ambient_temperature_K=0.0,
        )
    print("[thermal] solving linear system", flush=True)
    solved = solve_assembled_thermal_system(
        system,
        source_W_m3=q,
        relative_tolerance=1e-10,
        max_iterations=12000,
    )
    print("[thermal] linear solve complete", flush=True)
    flake_xy = np.any(geometry.flake_mask, axis=2)
    if args.geometry == "straight-45-edge":
        edge_metrics, fields = straight_edge_temperature_metrics(
            solved.temperature_K,
            geometry,
        )
        psi = None
        grad_x = None
        grad_y = None
        weighting = {
            "applied": False,
            "reason": (
                "straight-edge optical/thermal subgate intentionally precedes "
                "weighting-field and PTE-current evaluation"
            ),
        }
        weighting_passed = True
        current = None
        resistance_audit = None
    else:
        edge_metrics = None
        psi, grad_x, grad_y, weighting = solve_weighting_potential(
            geometry.x_edges_m, geometry.y_edges_m, flake_xy
        )
        current, fields = pte_current(
            solved.temperature_K, geometry, grad_x, grad_y
        )
        resistance_audit = audit_two_terminal_resistance(
            geometry.x_edges_m,
            geometry.y_edges_m,
            flake_xy,
        )
        weighting_passed = (
            weighting["top_contact_cells"] > 0
            and weighting["bottom_contact_cells"] > 0
            # Values are stored at cell centres, not on Dirichlet faces.
            and weighting["minimum_psi"] < 0.05
            and weighting["maximum_psi"] > 0.95
            and weighting["linear_residual_relative"] < 1e-8
        )
    cell_volume = (
        np.diff(geometry.x_edges_m)[:, None, None]
        * np.diff(geometry.y_edges_m)[None, :, None]
        * np.diff(geometry.z_edges_m)[None, None, :]
    )
    numerical_gates_passed = (
        mapping["mapping_relative_power_error"] < 0.005
        and solved.energy_balance_relative_error < 0.01
        and solved.linear_residual_relative < 1e-8
        and weighting_passed
    )
    if args.geometry == "straight-45-edge":
        completed_status = (
            "COMPLETED_STRAIGHT_45_EDGE_THERMAL_CONTROL"
            if args.thermal_model == "expanded"
            else "COMPLETED_STRAIGHT_45_EDGE_PAPER_REDUCED_CONTROL"
        )
        failed_status = "FAILED_STRAIGHT_45_EDGE_THERMAL_CONTROL"
    elif args.metal_thermalization == "isolated-lower-bound":
        completed_status = "COMPLETED_DEVICE_A_METAL_ISOLATED_LOWER_BOUND_DIAGNOSTIC"
        failed_status = "FAILED_DEVICE_A_METAL_ISOLATED_LOWER_BOUND_DIAGNOSTIC"
    elif args.metal_thermalization == "perfect-to-flake-upper-bound":
        completed_status = "COMPLETED_DEVICE_A_PERFECT_TO_FLAKE_UPPER_BOUND_DIAGNOSTIC"
        failed_status = "FAILED_DEVICE_A_PERFECT_TO_FLAKE_UPPER_BOUND_DIAGNOSTIC"
    else:
        # A finite-metal Device-A artifact should have failed closed in
        # load_and_map_q before reaching this point.
        completed_status = "COMPLETED_DEVICE_A_NO_METAL_Q_CONTROL"
        failed_status = "FAILED_DEVICE_A_NO_METAL_Q_CONTROL"
    summary = {
        "status": completed_status if numerical_gates_passed else failed_status,
        "model_identity": (
            (
                "current inverse-design expanded conservative Cartesian FVM; "
                "not the paper reduced Robin thermal model"
            )
            if args.thermal_model == "expanded"
            else (
                "paper Supplement Eq. S4 reduced flake-only Robin reference; "
                "not the current expanded production thermal model"
            )
        ),
        "metal_thermalization_scenario": args.metal_thermalization,
        "metal_thermalization_interpretation": (
            "diagnostic lower/upper bound only; not a paper-certified explicit "
            "Au/Ti thermal geometry or a measured metal/TaIrTe4 interface G"
        ),
        "published_parameters": {
            "TaIrTe4_thickness_m": THICKNESS_M,
            "kappa_a_b_c_W_mK": [14.4, 3.8, 1.0],
            "sigma_a_b_S_m": [4.91e5, 1.10e5],
            "Seebeck_a_b_V_K": [-6e-6, 27e-6],
            "G_TaIrTe4_air_W_m2K": G_TAIRTE4_AIR_W_M2K,
            "G_TaIrTe4_thermally_grown_SiO2_W_m2K": (
                G_TAIRTE4_THERMALLY_GROWN_SIO2_W_M2K
            ),
            "G_TaIrTe4_evaporated_SiO2_W_m2K": (
                G_TAIRTE4_EVAPORATED_SIO2_W_M2K
            ),
            "selected_TaIrTe4_SiO2_scenario": (
                args.tairte4_sio2_interface_scenario
            ),
            "selected_G_TaIrTe4_SiO2_W_m2K": selected_tairte4_sio2_G,
            "T_bath_K": T_BATH_K,
        },
        "expanded_model_parameters_not_supplied_by_paper": {
            "bulk_k_SiO2_W_mK": KAPPA_SIO2_W_MK,
            "bulk_k_Si_W_mK": KAPPA_SI_W_MK,
            "bulk_k_air_W_mK": KAPPA_AIR_W_MK,
            "G_SiO2_Si_W_m2K": G_SIO2_SI_W_M2K,
            "exposed_h_W_m2K": H_EXPOSED_W_M2K,
            "far_xy_boundary": "fixed DeltaT=0 numerical truncation",
            "bottom_boundary": "fixed DeltaT=0 numerical truncation",
        },
        "geometry": {
            "geometry_name": args.geometry,
            "flake_vertices_um": FLAKE_VERTICES_UM.tolist(),
            "flake_CAD_status": (
                "approximation from paper Figure 2A"
                if args.geometry == "device-a-polygon"
                else (
                    "corner-free paper-Figure-3F half-plane control; "
                    "TaIrTe4 occupies y<=x"
                )
            ),
            "contacts_status": weighting.get(
                "geometry_status",
                "not applied in the straight-edge thermal subgate",
            ),
            "thermal_domain_um": args.thermal_domain_um,
            "si_depth_um": args.si_depth_um,
            "core_step_nm": args.core_step_nm,
            "flake_dz_nm": args.flake_dz_nm,
            "grid_shape": list(geometry.material_id.shape),
            "thermal_model": args.thermal_model,
            "TaIrTe4_SiO2_interface_scenario": (
                args.tairte4_sio2_interface_scenario
            ),
            "TaIrTe4_SiO2_interface_G_W_m2K": selected_tairte4_sio2_G,
            "optical_coordinate_frame": {
                "case_result_path": str(optical_result_path.resolve()),
                "optical_domain_um": optical_domain_um,
                "optical_source_span_um": optical_source_span_um,
                "translation_loaded_from_actual_optical_contract": True,
                "thermal_domain_is_not_used_to_translate_optical_geometry": True,
            },
            "digitized_contract": (
                None
                if digitized_contract is None
                else {
                    key: value
                    for key, value in digitized_contract.items()
                    if key != "payload"
                }
            ),
            "metal_thermal_geometry": (
                "not included: the Au/Ti optical polygons are visible-area "
                "digitizations, while their hidden under-flake overlap and "
                "metal/TaIrTe4 thermal interface conductance are not published"
            ),
        },
        "mapping": mapping,
        "thermal": {
            "Tmax_rise_K": float(np.nanmax(solved.temperature_K)),
            "TaIrTe4_volume_average_rise_K": measure_weighted_mean(
                solved.temperature_K,
                geometry.flake_mask,
                cell_volume,
            ),
            "linear_residual_relative": solved.linear_residual_relative,
            "energy_balance_relative_error": solved.energy_balance_relative_error,
            "source_power_W": solved.source_power_W,
            "boundary_power_out_W": solved.boundary_power_out_W,
            "boundary_flux_interpretation": (
                "x/y and bottom Dirichlet entries are numerical truncation-"
                "boundary fluxes, not intrinsic physical heat-path fractions"
                if args.thermal_model == "expanded"
                else (
                    "surface_robin_z_min/z_max are the paper reduced model's "
                    "substrate/air bath heat paths"
                )
            ),
            "solver": solved.solver,
            "iterations": solved.iterations,
        },
        "weighting": weighting,
        "weighting_gate_passed": weighting_passed,
        "two_terminal_resistance_audit": resistance_audit,
        "absolute_current_certification": (
            "not_applicable_straight_edge_control"
            if resistance_audit is None
            else (
                "GEOMETRY_RESISTANCE_GATE_PASSED"
                if resistance_audit["absolute_current_geometry_gate_lt_10pct"]
                else "BLOCKED_DIGITIZED_GEOMETRY_RESISTANCE_MISMATCH"
            )
        ),
        "PTE_current_A_at_requested_incident_power": current,
        "PTE_current_pA_at_requested_incident_power": (
            None if current is None else current * 1e12
        ),
        "requested_incident_power_W": args.incident_power_uw * 1.0e-6,
        # Backward-compatible keys are retained because several frozen
        # checkpoint summarizers consume them.  They are historical labels,
        # not an assertion that a non-default run used exactly 285 uW.
        "PTE_current_A_at_285uW_incident": current,
        "PTE_current_pA_at_285uW_incident": (
            None if current is None else current * 1e12
        ),
        "legacy_285uW_key_interpretation": (
            "backward-compatible field name; authoritative power is "
            "requested_incident_power_W"
        ),
        "PTE_current_integration_contract": (
            None
            if current is None
            else {
                "primary": "full flake-cell volume integral in A",
                "secondary": "dz-integrated sheet form in A",
                "volume_area_relative_difference": float(
                    fields["PTE_volume_area_equivalence_relative_error"][0]
                ),
                "volume_integral_A": float(
                    fields["PTE_current_volume_integral_A"][0]
                ),
                "thickness_integrated_area_A": float(
                    fields["PTE_current_thickness_integrated_area_A"][0]
                ),
            }
        ),
        "straight_edge_metrics": edge_metrics,
        "no_optimization": True,
        "no_gradient": True,
    }
    summary = jsonable(summary)
    (args.output_dir / "summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    field_payload = {
        "x_edges_m": geometry.x_edges_m,
        "y_edges_m": geometry.y_edges_m,
        "z_edges_m": geometry.z_edges_m,
        "flake_mask": geometry.flake_mask,
        "Q_W_m3": q,
        "temperature_rise_K": solved.temperature_K,
        **fields,
    }
    if psi is not None:
        field_payload.update(
            {
                "weighting_potential": psi,
                "weighting_grad_x_m_inv": grad_x,
                "weighting_grad_y_m_inv": grad_y,
            }
        )
    np.savez(
        args.output_dir / "thermal_pte_fields.npz",
        **field_payload,
    )

    x = 0.5 * (geometry.x_edges_m[:-1] + geometry.x_edges_m[1:]) * 1e6
    y = 0.5 * (geometry.y_edges_m[:-1] + geometry.y_edges_m[1:]) * 1e6
    extent = [x[0], x[-1], y[0], y[-1]]
    areal_q = np.sum(
        q * np.diff(geometry.z_edges_m)[None, None, :],
        axis=2,
    )
    if args.geometry == "straight-45-edge":
        fig, axes = plt.subplots(
            2,
            2,
            figsize=(12, 10),
            constrained_layout=True,
        )
        images = (
            (areal_q, "absorbed areal power (W/m²)", "inferno"),
            (
                fields["temperature_flake_average_K"],
                "TaIrTe4 ΔT (K)",
                "inferno",
            ),
            (
                np.abs(fields["grad_T_normal_K_m"]),
                "|edge-normal ∂T/∂n| (K/m)",
                "magma",
            ),
            (
                fields["grad_T_magnitude_K_m"],
                "|in-plane ∇T| (K/m)",
                "magma",
            ),
        )
        title = (
            "Straight 45° edge: Lumerical Q → expanded thermal FVM "
            "(no weighting/PTE)"
        )
        figure_name = "straight_45_edge_thermal_control.png"
    else:
        fig, axes = plt.subplots(
            2,
            2,
            figsize=(12, 10),
            constrained_layout=True,
        )
        images = (
            (areal_q, "absorbed areal power (W/m²)", "inferno"),
            (
                fields["temperature_flake_average_K"],
                "TaIrTe4 ΔT (K)",
                "inferno",
            ),
            (psi, "weighting potential ψ", "viridis"),
            (
                fields["shockley_ramo_integrand_A_m2"],
                "PTE collection integrand",
                "RdBu_r",
            ),
        )
        title = "Device-A IR sanity: Lumerical Q → expanded thermal FVM → PTE"
        figure_name = "device_a_ir_thermal_pte.png"
    for ax, (image, panel_title, cmap) in zip(axes.ravel(), images):
        if "∂T/∂n" in panel_title or "∇T" in panel_title:
            strict = strict_centered_xy_mask(
                np.any(geometry.flake_mask, axis=2)
            )
            image = np.where(strict, image, np.nan)
        handle = cell_field(
            ax,
            geometry.x_edges_m,
            geometry.y_edges_m,
            image,
            coordinate_scale=1e6,
            cmap=cmap,
        )
        if args.geometry == "straight-45-edge":
            ax.plot(
                [extent[0], extent[1]],
                [extent[0], extent[1]],
                color="cyan",
                ls="--",
                lw=0.8,
            )
        ax.set(
            title=panel_title,
            xlabel="lab x = b (µm)",
            ylabel="lab y = a (µm)",
        )
        fig.colorbar(handle, ax=ax)
    fig.suptitle(title)
    fig.savefig(args.output_dir / figure_name, dpi=200)
    plt.close(fig)
    print(json.dumps(summary, indent=2))
    return 0 if summary["status"].startswith("COMPLETED") else 2


if __name__ == "__main__":
    raise SystemExit(main())
