#!/usr/bin/env python3
"""Map Lumerical 11 um Q into the current explicit-boundary thermal FVM.

The optical artifact is generated by ``run_lumerical_device_a_ir_q.py``.
This script intentionally uses the *expanded production thermal model*:

* explicit bulk Si, 285 nm SiO2, TaIrTe4, and air cells;
* TaIrTe4/SiO2, TaIrTe4/air, and SiO2/Si interface resistances;
* fixed far-x/y and bottom numerical boundaries; and
* exposed top-surface convection.

Those assumptions are not mislabeled as the paper's reduced Robin model.
The flake and contacts are explicit, documented approximations to Device A.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.path import Path as PolygonPath
import numpy as np
from scipy import sparse
from scipy.ndimage import distance_transform_edt
from scipy.sparse import linalg as spla


HERE = Path(__file__).resolve().parent
REPOSITORY = HERE.parents[2]
FVM_DIR = HERE.parent / "photothermal_stage1"
for location in (REPOSITORY, FVM_DIR):
    if str(location) not in sys.path:
        sys.path.insert(0, str(location))

from anisotropic_heat_fvm import (  # noqa: E402
    assemble_steady_diagonal_kappa,
    solve_assembled_thermal_system,
)
from photothermal_pte.finite_inverse_design.finite_q_mapping import (  # noqa: E402
    build_conservative_embedding_remap,
    nodal_control_volume_edges,
    project_remap_to_material_support_along_axis,
)


T_BATH_K = 300.0
THICKNESS_M = 130.0e-9
SIO2_THICKNESS_M = 285.0e-9
AIR_HEIGHT_M = 600.0e-9
KAPPA_TAIRTE4_LAB_W_MK = np.asarray([3.8, 14.4, 1.0])  # lab x=b, y=a
KAPPA_SIO2_W_MK = 1.38
KAPPA_SI_W_MK = 145.0
KAPPA_AIR_W_MK = 0.026
G_TAIRTE4_AIR_W_M2K = 1.0
G_TAIRTE4_SIO2_W_M2K = 7.37e6
G_SIO2_SI_W_M2K = 1.1e9
H_EXPOSED_W_M2K = 10.0
SIGMA_LAB_S_M = np.asarray([1.10e5, 4.91e5])  # b, a
SEEBECK_LAB_V_K = np.asarray([27.0e-6, -6.0e-6])  # b, a
EXPERIMENTAL_INCIDENT_POWER_W = 285.0e-6

FLAKE_VERTICES_UM = np.asarray(
    [
        [-11.0, -10.0],
        [12.0, -10.0],
        [12.0, 10.0],
        [-6.0, 10.0],
        [-6.0, 6.0],
        [-11.0, 1.0],
    ]
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def growing_positions(
    length_m: float,
    initial_step_m: float,
    maximum_step_m: float,
    growth: float = 1.4,
) -> np.ndarray:
    values = [0.0]
    step = initial_step_m
    while values[-1] + step < length_m:
        values.append(values[-1] + step)
        step = min(maximum_step_m, growth * step)
    values.append(length_m)
    return np.unique(np.asarray(values))


def lateral_edges(domain_m: float, core_step_m: float) -> np.ndarray:
    core_min, core_max = -12.0e-6, 12.0e-6
    cells = int(round((core_max - core_min) / core_step_m))
    if not np.isclose(cells * core_step_m, core_max - core_min):
        raise ValueError("core step must divide the 24 um Device-A core")
    core = np.linspace(core_min, core_max, cells + 1)
    half = 0.5 * domain_m
    if half <= core_max:
        raise ValueError("thermal domain must extend beyond Device A")
    outer = growing_positions(
        half - core_max,
        initial_step_m=core_step_m,
        maximum_step_m=1.0e-6,
    )[1:]
    return np.concatenate((-12.0e-6 - outer[::-1], core, 12.0e-6 + outer))


def z_edges(si_depth_m: float, flake_dz_m: float) -> np.ndarray:
    if not np.isclose(round(THICKNESS_M / flake_dz_m) * flake_dz_m, THICKNESS_M):
        raise ValueError("flake dz must divide 130 nm")
    si_top = -(THICKNESS_M + SIO2_THICKNESS_M)
    si = si_top - growing_positions(
        si_depth_m, initial_step_m=25e-9, maximum_step_m=0.5e-6, growth=1.35
    )[::-1]
    oxide = np.linspace(si_top, -THICKNESS_M, 20)
    flake = np.linspace(
        -THICKNESS_M,
        0.0,
        int(round(THICKNESS_M / flake_dz_m)) + 1,
    )
    air = np.linspace(0.0, AIR_HEIGHT_M, 7)
    edges = np.concatenate((si, oxide[1:], flake[1:], air[1:]))
    if np.any(np.diff(edges) <= 0):
        raise RuntimeError("z grid is not strictly increasing")
    return edges


def polygon_mask(x_m: np.ndarray, y_m: np.ndarray) -> np.ndarray:
    xx, yy = np.meshgrid(x_m, y_m, indexing="ij")
    points = np.column_stack((xx.ravel(), yy.ravel()))
    return PolygonPath(FLAKE_VERTICES_UM * 1e-6).contains_points(
        points, radius=1e-15
    ).reshape(xx.shape)


@dataclass(frozen=True)
class Geometry:
    x_edges_m: np.ndarray
    y_edges_m: np.ndarray
    z_edges_m: np.ndarray
    material_id: np.ndarray
    flake_mask: np.ndarray
    kappa_W_mK: np.ndarray
    interface_resistance_m2K_W: dict[str, np.ndarray]


def build_geometry(
    *,
    domain_m: float,
    si_depth_m: float,
    core_step_m: float,
    flake_dz_m: float,
) -> Geometry:
    x_edges = lateral_edges(domain_m, core_step_m)
    y_edges = lateral_edges(domain_m, core_step_m)
    z_edge = z_edges(si_depth_m, flake_dz_m)
    x = 0.5 * (x_edges[:-1] + x_edges[1:])
    y = 0.5 * (y_edges[:-1] + y_edges[1:])
    z = 0.5 * (z_edge[:-1] + z_edge[1:])
    shape = (x.size, y.size, z.size)
    material = np.zeros(shape, np.uint8)  # air
    si = z < -(THICKNESS_M + SIO2_THICKNESS_M)
    oxide = (z > -(THICKNESS_M + SIO2_THICKNESS_M)) & (z < -THICKNESS_M)
    flake_z = (z > -THICKNESS_M) & (z < 0.0)
    material[:, :, si] = 1
    material[:, :, oxide] = 2
    flake_xy = polygon_mask(x, y)
    flake = flake_xy[:, :, None] & flake_z[None, None, :]
    material[flake] = 3

    kappa = np.full((*shape, 3), KAPPA_AIR_W_MK)
    kappa[material == 1] = KAPPA_SI_W_MK
    kappa[material == 2] = KAPPA_SIO2_W_MK
    kappa[material == 3] = KAPPA_TAIRTE4_LAB_W_MK
    rx = np.zeros((shape[0] - 1, shape[1], shape[2]))
    ry = np.zeros((shape[0], shape[1] - 1, shape[2]))
    rz = np.zeros((shape[0], shape[1], shape[2] - 1))
    left, right = material[:-1], material[1:]
    rx[((left == 3) & (right == 0)) | ((left == 0) & (right == 3))] = (
        1.0 / G_TAIRTE4_AIR_W_M2K
    )
    low, high = material[:, :-1], material[:, 1:]
    ry[((low == 3) & (high == 0)) | ((low == 0) & (high == 3))] = (
        1.0 / G_TAIRTE4_AIR_W_M2K
    )
    lower, upper = material[:, :, :-1], material[:, :, 1:]
    rz[((lower == 1) & (upper == 2)) | ((lower == 2) & (upper == 1))] = (
        1.0 / G_SIO2_SI_W_M2K
    )
    rz[((lower == 2) & (upper == 3)) | ((lower == 3) & (upper == 2))] = (
        1.0 / G_TAIRTE4_SIO2_W_M2K
    )
    rz[((lower == 3) & (upper == 0)) | ((lower == 0) & (upper == 3))] = (
        1.0 / G_TAIRTE4_AIR_W_M2K
    )
    return Geometry(
        x_edges,
        y_edges,
        z_edge,
        material,
        flake,
        kappa,
        {"x": rx, "y": ry, "z": rz},
    )


def reduced_flake_geometry(
    expanded: Geometry,
    q_expanded: np.ndarray,
) -> tuple[Geometry, np.ndarray]:
    """Extract the paper Eq. S4 sheet-like Robin reference from one grid."""
    selected_z = np.flatnonzero(np.any(expanded.flake_mask, axis=(0, 1)))
    if selected_z.size == 0 or not np.all(np.diff(selected_z) == 1):
        raise RuntimeError("cannot identify contiguous flake z cells")
    start, stop = int(selected_z[0]), int(selected_z[-1] + 1)
    z_edges = expanded.z_edges_m[start : stop + 1]
    flake_xy = np.any(expanded.flake_mask, axis=2)
    flake = np.broadcast_to(
        flake_xy[:, :, None],
        (flake_xy.shape[0], flake_xy.shape[1], selected_z.size),
    ).copy()
    material = np.zeros(flake.shape, np.uint8)
    material[flake] = 3
    kappa = np.ones((*flake.shape, 3), float)
    kappa[flake] = KAPPA_TAIRTE4_LAB_W_MK
    resistances = {
        "x": np.zeros((flake.shape[0] - 1, flake.shape[1], flake.shape[2])),
        "y": np.zeros((flake.shape[0], flake.shape[1] - 1, flake.shape[2])),
        "z": np.zeros((flake.shape[0], flake.shape[1], flake.shape[2] - 1)),
    }
    return (
        Geometry(
            expanded.x_edges_m,
            expanded.y_edges_m,
            z_edges,
            material,
            flake,
            kappa,
            resistances,
        ),
        q_expanded[:, :, start:stop],
    )


def solve_weighting_potential(
    x_edges_m: np.ndarray,
    y_edges_m: np.ndarray,
    flake_xy: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, dict[str, Any]]:
    """Finite-volume Eq. S7 with approximate full-width top/bottom contacts."""
    x = 0.5 * (x_edges_m[:-1] + x_edges_m[1:])
    y = 0.5 * (y_edges_m[:-1] + y_edges_m[1:])
    dx, dy = np.diff(x_edges_m), np.diff(y_edges_m)
    ids = np.full(flake_xy.shape, -1, np.int64)
    ids[flake_xy] = np.arange(np.count_nonzero(flake_xy))
    n = int(np.count_nonzero(flake_xy))
    diagonal = np.zeros(n)
    rows: list[np.ndarray] = []
    cols: list[np.ndarray] = []
    vals: list[np.ndarray] = []
    for axis in (0, 1):
        if axis == 0:
            lhs, rhs = ids[:-1], ids[1:]
            conductance = (
                2.0 * dy[None, :] / (dx[:-1, None] + dx[1:, None])
            )
        else:
            lhs, rhs = ids[:, :-1], ids[:, 1:]
            conductance = (
                2.0 * dx[:, None] / (dy[None, :-1] + dy[None, 1:])
            )
        connected = (lhs >= 0) & (rhs >= 0)
        left_id, right_id = lhs[connected], rhs[connected]
        g = np.broadcast_to(conductance, lhs.shape)[connected]
        np.add.at(diagonal, left_id, g)
        np.add.at(diagonal, right_id, g)
        rows += [left_id, right_id]
        cols += [right_id, left_id]
        vals += [-g, -g]

    # Contacts inferred from Fig. 2A: top/bottom bars cover broad exterior
    # boundary segments. Detect the exterior faces topologically so the
    # contract does not depend on cell-centre equality at +/-9.9 um.
    neighbour_above = np.zeros_like(flake_xy)
    neighbour_above[:, :-1] = flake_xy[:, 1:]
    neighbour_below = np.zeros_like(flake_xy)
    neighbour_below[:, 1:] = flake_xy[:, :-1]
    top_boundary = flake_xy & ~neighbour_above
    bottom_boundary = flake_xy & ~neighbour_below
    top = top_boundary & (y[None, :] > 8.0e-6) & (x[:, None] > -5.8e-6)
    bottom = bottom_boundary & (y[None, :] < -8.0e-6) & (x[:, None] > -10.5e-6)
    if not np.any(top) or not np.any(bottom):
        raise RuntimeError(
            f"contact discretization failed: top={np.count_nonzero(top)}, "
            f"bottom={np.count_nonzero(bottom)}"
        )
    load = np.zeros(n)
    for selected, value, half_width, area in (
        (top, 1.0, 0.5 * dy[-1], dx[:, None]),
        (bottom, 0.0, 0.5 * dy[0], dx[:, None]),
    ):
        flat = ids[selected]
        g = np.broadcast_to(area / half_width, ids.shape)[selected]
        np.add.at(diagonal, flat, g)
        np.add.at(load, flat, g * value)
    matrix = sparse.diags(diagonal) + sparse.coo_matrix(
        (np.concatenate(vals), (np.concatenate(rows), np.concatenate(cols))),
        shape=(n, n),
    ).tocsr()
    psi_active = spla.spsolve(matrix.tocsc(), load)
    residual = np.linalg.norm(matrix @ psi_active - load) / max(
        np.linalg.norm(load), np.finfo(float).tiny
    )
    psi = np.full(ids.shape, np.nan)
    psi[flake_xy] = psi_active
    grad_x, grad_y = cell_gradient(psi, flake_xy, x, y)
    return psi, grad_x, grad_y, {
        "top_contact_cells": int(np.count_nonzero(top)),
        "bottom_contact_cells": int(np.count_nonzero(bottom)),
        "minimum_psi": float(np.nanmin(psi)),
        "maximum_psi": float(np.nanmax(psi)),
        "linear_residual_relative": float(residual),
        "geometry_status": "approximate contacts inferred from paper Figure 2A",
    }


def cell_gradient(
    field: np.ndarray,
    mask: np.ndarray,
    x_m: np.ndarray,
    y_m: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    gx = np.zeros_like(field)
    gy = np.zeros_like(field)
    for i, j in zip(*np.nonzero(mask)):
        if i > 0 and i + 1 < field.shape[0] and mask[i - 1, j] and mask[i + 1, j]:
            gx[i, j] = (field[i + 1, j] - field[i - 1, j]) / (x_m[i + 1] - x_m[i - 1])
        elif i + 1 < field.shape[0] and mask[i + 1, j]:
            gx[i, j] = (field[i + 1, j] - field[i, j]) / (x_m[i + 1] - x_m[i])
        elif i > 0 and mask[i - 1, j]:
            gx[i, j] = (field[i, j] - field[i - 1, j]) / (x_m[i] - x_m[i - 1])
        if j > 0 and j + 1 < field.shape[1] and mask[i, j - 1] and mask[i, j + 1]:
            gy[i, j] = (field[i, j + 1] - field[i, j - 1]) / (y_m[j + 1] - y_m[j - 1])
        elif j + 1 < field.shape[1] and mask[i, j + 1]:
            gy[i, j] = (field[i, j + 1] - field[i, j]) / (y_m[j + 1] - y_m[j])
        elif j > 0 and mask[i, j - 1]:
            gy[i, j] = (field[i, j] - field[i, j - 1]) / (y_m[j] - y_m[j - 1])
    return gx, gy


def load_and_map_q(
    artifact_path: Path,
    result_path: Path,
    geometry: Geometry,
) -> tuple[np.ndarray, dict[str, Any]]:
    result = json.loads(result_path.read_text())
    if result.get("status") != "COMPLETED":
        raise RuntimeError("optical case did not complete")
    with np.load(artifact_path, allow_pickle=False) as raw:
        x = np.asarray(raw["x_m"], float)
        y = np.asarray(raw["y_m"], float)
        z = np.asarray(raw["z_m"], float)
        q = np.asarray(raw["Q_on_W_m3"], float)
    source_edges = tuple(nodal_control_volume_edges(axis) for axis in (x, y, z))
    target_edges = (geometry.x_edges_m, geometry.y_edges_m, geometry.z_edges_m)
    remap = build_conservative_embedding_remap(
        source_edges_m=source_edges,
        target_edges_m=target_edges,
    )
    for axis in (0, 1, 2, 0):
        remap = project_remap_to_material_support_along_axis(
            remap,
            target_edges_m=target_edges,
            target_support_mask=geometry.flake_mask,
            axis=axis,
        )
    incident_at_unit = float(
        result["run_result"]["normalization"]["incident_power_W_at_1_W_m2"]
    )
    physical_scale = EXPERIMENTAL_INCIDENT_POWER_W / incident_at_unit
    mapped = remap.apply(q * physical_scale)
    p_source = remap.power_source(q * physical_scale)
    target_volume = remap.target_volume_m3
    outside_power_before = float(
        np.sum(remap.target_volume_m3[~geometry.flake_mask] * mapped[~geometry.flake_mask])
    )
    # A final literal energy projection closes polygon/support discretization
    # at oblique edges. It moves energy; it never deletes or globally rescales
    # it. The before/after power is retained as a diagnostic.
    energy = mapped * target_volume
    outside_nonzero = (~geometry.flake_mask) & (energy != 0.0)
    if np.any(outside_nonzero):
        nearest = distance_transform_edt(
            ~geometry.flake_mask,
            return_distances=False,
            return_indices=True,
        )
        destinations = tuple(
            nearest[axis][outside_nonzero] for axis in range(3)
        )
        moved = energy[outside_nonzero].copy()
        energy[outside_nonzero] = 0.0
        np.add.at(energy, destinations, moved)
        mapped = energy / target_volume
    p_target = remap.power_target(mapped)
    outside_power = float(
        np.sum(target_volume[~geometry.flake_mask] * mapped[~geometry.flake_mask])
    )
    return mapped, {
        "optical_artifact_path": str(artifact_path.resolve()),
        "optical_artifact_sha256": sha256(artifact_path),
        "optical_result_path": str(result_path.resolve()),
        "optical_result_sha256": sha256(result_path),
        "experimental_incident_power_W": EXPERIMENTAL_INCIDENT_POWER_W,
        "unit_central_intensity_incident_power_W": incident_at_unit,
        "physical_incident_power_scale": physical_scale,
        "P_Q_source_W": p_source,
        "P_Q_target_W": p_target,
        "mapping_relative_power_error": abs(p_target - p_source) / abs(p_source),
        "mapped_power_outside_flake_before_final_support_W": outside_power_before,
        "mapped_power_outside_flake_before_final_support_fraction": (
            outside_power_before / p_source
        ),
        "mapped_power_outside_flake_W": outside_power,
        "mapping_operations": (
            "validated linear conservative embedding plus x/y/z/x "
            "material-support projection and a final nearest-support cell-energy "
            "projection at the oblique polygon edge; no clipping, smoothing, "
            "gain, global rescaling, or tiling"
        ),
    }


def pte_current(
    temperature_K: np.ndarray,
    geometry: Geometry,
    grad_psi_x: np.ndarray,
    grad_psi_y: np.ndarray,
) -> tuple[float, dict[str, np.ndarray]]:
    x = 0.5 * (geometry.x_edges_m[:-1] + geometry.x_edges_m[1:])
    y = 0.5 * (geometry.y_edges_m[:-1] + geometry.y_edges_m[1:])
    dz = np.diff(geometry.z_edges_m)
    flake_z = np.flatnonzero(np.any(geometry.flake_mask, axis=(0, 1)))
    thickness = float(np.sum(dz[flake_z]))
    average = np.sum(
        temperature_K[:, :, flake_z] * dz[flake_z][None, None, :], axis=2
    ) / thickness
    mask = np.any(geometry.flake_mask, axis=2)
    grad_tx, grad_ty = cell_gradient(average, mask, x, y)
    local_x = -SIGMA_LAB_S_M[0] * SEEBECK_LAB_V_K[0] * grad_tx
    local_y = -SIGMA_LAB_S_M[1] * SEEBECK_LAB_V_K[1] * grad_ty
    area = np.diff(geometry.x_edges_m)[:, None] * np.diff(geometry.y_edges_m)[None, :]
    density = (local_x * grad_psi_x + local_y * grad_psi_y) * thickness
    current = float(np.sum(density[mask] * area[mask]))
    return current, {
        "temperature_flake_average_K": average,
        "grad_T_x_K_m": grad_tx,
        "grad_T_y_K_m": grad_ty,
        "local_J_x_A_m2": local_x,
        "local_J_y_A_m2": local_y,
        "shockley_ramo_integrand_A_m2": density,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--optical-case-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--thermal-domain-um", type=float, default=48.0)
    parser.add_argument("--si-depth-um", type=float, default=20.0)
    parser.add_argument("--core-step-nm", type=float, default=200.0)
    parser.add_argument("--flake-dz-nm", type=float, default=26.0)
    parser.add_argument(
        "--thermal-model",
        choices=("expanded", "paper-reduced"),
        default="expanded",
    )
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=False)
    geometry = build_geometry(
        domain_m=args.thermal_domain_um * 1e-6,
        si_depth_m=args.si_depth_um * 1e-6,
        core_step_m=args.core_step_nm * 1e-9,
        flake_dz_m=args.flake_dz_nm * 1e-9,
    )
    q, mapping = load_and_map_q(
        args.optical_case_dir / "finite_q_on_artifact.npz",
        args.optical_case_dir / "case_result.json",
        geometry,
    )
    expanded_geometry = geometry
    if args.thermal_model == "paper-reduced":
        geometry, q = reduced_flake_geometry(geometry, q)
        system = assemble_steady_diagonal_kappa(
            x_edges_m=geometry.x_edges_m,
            y_edges_m=geometry.y_edges_m,
            z_edges_m=geometry.z_edges_m,
            kappa_W_mK=geometry.kappa_W_mK,
            dirichlet_temperature_K={},
            interface_resistance_m2K_W=geometry.interface_resistance_m2K_W,
            active_mask=geometry.flake_mask,
            surface_robin_heat_transfer_W_m2K={
                "z_min": G_TAIRTE4_SIO2_W_M2K,
                "z_max": G_TAIRTE4_AIR_W_M2K,
            },
            surface_robin_temperature_K={"z_min": 0.0, "z_max": 0.0},
        )
    else:
        system = assemble_steady_diagonal_kappa(
            x_edges_m=geometry.x_edges_m,
            y_edges_m=geometry.y_edges_m,
            z_edges_m=geometry.z_edges_m,
            kappa_W_mK=geometry.kappa_W_mK,
            dirichlet_temperature_K={
                "x_min": 0.0,
                "x_max": 0.0,
                "y_min": 0.0,
                "y_max": 0.0,
                "z_min": 0.0,
            },
            interface_resistance_m2K_W=geometry.interface_resistance_m2K_W,
            active_mask=np.ones(geometry.material_id.shape, bool),
            exposed_heat_transfer_W_m2K=H_EXPOSED_W_M2K,
            ambient_temperature_K=0.0,
        )
    solved = solve_assembled_thermal_system(
        system,
        source_W_m3=q,
        relative_tolerance=1e-10,
        max_iterations=12000,
    )
    flake_xy = np.any(geometry.flake_mask, axis=2)
    psi, grad_x, grad_y, weighting = solve_weighting_potential(
        geometry.x_edges_m, geometry.y_edges_m, flake_xy
    )
    current, fields = pte_current(
        solved.temperature_K, geometry, grad_x, grad_y
    )
    flake_temperature = solved.temperature_K[geometry.flake_mask]
    weighting_passed = (
        weighting["top_contact_cells"] > 0
        and weighting["bottom_contact_cells"] > 0
        # Values are stored at cell centres, not on Dirichlet faces.
        and weighting["minimum_psi"] < 0.05
        and weighting["maximum_psi"] > 0.95
        and weighting["linear_residual_relative"] < 1e-8
    )
    summary = {
        "status": (
            (
                "COMPLETED_DEVICE_A_EXPANDED_THERMAL_PTE_SANITY"
                if args.thermal_model == "expanded"
                else "COMPLETED_DEVICE_A_PAPER_REDUCED_THERMAL_PTE_REFERENCE"
            )
            if (
                mapping["mapping_relative_power_error"] < 0.005
                and solved.energy_balance_relative_error < 0.01
                and solved.linear_residual_relative < 1e-8
                and weighting_passed
            )
            else "FAILED_DEVICE_A_EXPANDED_THERMAL_PTE_SANITY"
        ),
        "model_identity": (
            (
                "current inverse-design expanded conservative Cartesian FVM; "
                "not the paper reduced Robin thermal model"
            )
            if args.thermal_model == "expanded"
            else (
                "paper Supplement Eq. S4 reduced flake-only Robin reference; "
                "not the current expanded production thermal model"
            )
        ),
        "published_parameters": {
            "TaIrTe4_thickness_m": THICKNESS_M,
            "kappa_a_b_c_W_mK": [14.4, 3.8, 1.0],
            "sigma_a_b_S_m": [4.91e5, 1.10e5],
            "Seebeck_a_b_V_K": [-6e-6, 27e-6],
            "G_TaIrTe4_air_W_m2K": G_TAIRTE4_AIR_W_M2K,
            "G_TaIrTe4_thermal_SiO2_W_m2K": G_TAIRTE4_SIO2_W_M2K,
            "T_bath_K": T_BATH_K,
        },
        "expanded_model_parameters_not_supplied_by_paper": {
            "bulk_k_SiO2_W_mK": KAPPA_SIO2_W_MK,
            "bulk_k_Si_W_mK": KAPPA_SI_W_MK,
            "bulk_k_air_W_mK": KAPPA_AIR_W_MK,
            "G_SiO2_Si_W_m2K": G_SIO2_SI_W_M2K,
            "exposed_h_W_m2K": H_EXPOSED_W_M2K,
            "far_xy_boundary": "fixed DeltaT=0 numerical truncation",
            "bottom_boundary": "fixed DeltaT=0 numerical truncation",
        },
        "geometry": {
            "flake_vertices_um": FLAKE_VERTICES_UM.tolist(),
            "flake_CAD_status": "approximation from paper Figure 2A",
            "contacts_status": weighting["geometry_status"],
            "thermal_domain_um": args.thermal_domain_um,
            "si_depth_um": args.si_depth_um,
            "core_step_nm": args.core_step_nm,
            "flake_dz_nm": args.flake_dz_nm,
            "grid_shape": list(geometry.material_id.shape),
            "thermal_model": args.thermal_model,
        },
        "mapping": mapping,
        "thermal": {
            "Tmax_rise_K": float(np.nanmax(solved.temperature_K)),
            "TaIrTe4_volume_average_rise_K": float(np.mean(flake_temperature)),
            "linear_residual_relative": solved.linear_residual_relative,
            "energy_balance_relative_error": solved.energy_balance_relative_error,
            "source_power_W": solved.source_power_W,
            "boundary_power_out_W": solved.boundary_power_out_W,
            "solver": solved.solver,
            "iterations": solved.iterations,
        },
        "weighting": weighting,
        "weighting_gate_passed": weighting_passed,
        "PTE_current_A_at_285uW_incident": current,
        "PTE_current_pA_at_285uW_incident": current * 1e12,
        "no_optimization": True,
        "no_gradient": True,
    }
    (args.output_dir / "summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    np.savez(
        args.output_dir / "thermal_pte_fields.npz",
        x_edges_m=geometry.x_edges_m,
        y_edges_m=geometry.y_edges_m,
        z_edges_m=geometry.z_edges_m,
        flake_mask=geometry.flake_mask,
        Q_W_m3=q,
        temperature_rise_K=solved.temperature_K,
        weighting_potential=psi,
        weighting_grad_x_m_inv=grad_x,
        weighting_grad_y_m_inv=grad_y,
        **fields,
    )

    x = 0.5 * (geometry.x_edges_m[:-1] + geometry.x_edges_m[1:]) * 1e6
    y = 0.5 * (geometry.y_edges_m[:-1] + geometry.y_edges_m[1:]) * 1e6
    extent = [x[0], x[-1], y[0], y[-1]]
    fig, axes = plt.subplots(2, 2, figsize=(12, 10), constrained_layout=True)
    images = (
        (np.sum(q * np.diff(geometry.z_edges_m)[None, None, :], axis=2), "absorbed areal power (W/m²)", "inferno"),
        (fields["temperature_flake_average_K"], "TaIrTe4 ΔT (K)", "inferno"),
        (psi, "weighting potential ψ", "viridis"),
        (fields["shockley_ramo_integrand_A_m2"], "PTE collection integrand", "RdBu_r"),
    )
    for ax, (image, title, cmap) in zip(axes.ravel(), images):
        handle = ax.imshow(image.T, origin="lower", extent=extent, aspect="equal", cmap=cmap)
        ax.set(title=title, xlabel="lab x = b (µm)", ylabel="lab y = a (µm)")
        fig.colorbar(handle, ax=ax)
    fig.suptitle("Device-A IR sanity: Lumerical Q → expanded thermal FVM → PTE")
    fig.savefig(args.output_dir / "device_a_ir_thermal_pte.png", dpi=200)
    plt.close(fig)
    print(json.dumps(summary, indent=2))
    return 0 if summary["status"].startswith("COMPLETED") else 2


if __name__ == "__main__":
    raise SystemExit(main())
