#!/usr/bin/env python3
"""Publish the Run-002 fixed-Q thermal-material AD--FD endpoint checks."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


HERE = Path(__file__).resolve().parent
RESULTS = HERE / "results"
PLOTS = HERE / "plots"
MANIFEST = HERE / "manifests" / "RAW_ARTIFACT_MANIFEST.json"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def record(path: Path) -> dict[str, object]:
    return {"path": str(path), "size_bytes": path.stat().st_size, "sha256": sha256(path)}


def load_case(directory: Path) -> tuple[dict[str, object], list[dict[str, object]]]:
    directory = directory.expanduser().resolve()
    result_path = directory / "production_thermal_material_adfd_result.json"
    result = json.loads(result_path.read_text())
    artifact = Path(result["raw_artifact"]["path"])
    if artifact.stat().st_size != result["raw_artifact"]["size_bytes"] or sha256(artifact) != result["raw_artifact"]["sha256"]:
        raise RuntimeError(f"raw artifact provenance mismatch: {directory}")
    return result, [record(result_path), record(artifact)]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--grown-grown", type=Path, required=True)
    parser.add_argument("--evaporated-evaporated", type=Path, required=True)
    args = parser.parse_args()
    inputs = {
        "grown_grown": args.grown_grown,
        "evaporated_evaporated": args.evaporated_evaporated,
    }
    cases: dict[str, dict[str, object]] = {}
    artifacts: dict[str, object] = {}
    for scenario, directory in inputs.items():
        result, files = load_case(directory)
        if result["scenario"] != scenario:
            raise RuntimeError(f"scenario mismatch: {scenario}")
        dot = max(row["dot_error"] for row in result["mapping_checks"])
        mapping_fd = max(row["FD_error"] for row in result["mapping_checks"])
        corrected_pass = bool(
            dot < 1e-12
            and mapping_fd < 1e-8
            and max(result["forward"]["residual"], result["adjoint"]["residual"]) < 1e-8
            and result["energy_balance_error"] < 0.01
            and result["best_FD_relative_error"] < 0.01
        )
        if not corrected_pass:
            raise RuntimeError(f"corrected endpoint gate did not pass: {scenario}")
        cases[scenario] = {
            **result,
            "published_corrected_gate_pass": True,
            "raw_status_preserved": result["status"],
            "raw_passed_preserved": result["passed"],
            "published_mapping_worst_dot_error": dot,
            "published_mapping_worst_FD_error": mapping_fd,
        }
        artifacts[scenario] = {
            "raw_directory": str(directory.expanduser().resolve()),
            "artifacts": files,
        }

    grown = cases["grown_grown"]
    if grown["raw_passed_preserved"] is not False:
        raise RuntimeError("expected the immutable grown/grown over-strict diagnostic failure")
    evaporated = cases["evaporated_evaporated"]
    if evaporated["raw_passed_preserved"] is not True:
        raise RuntimeError("evaporated endpoint was not generated by the corrected gate")

    status = "VALIDATED_PRODUCTION_FIXED_Q_THERMAL_MATERIAL_ADFD_ENDPOINTS"
    summary = {
        "status": status,
        "passed": True,
        "scope": (
            "fixed rho=0.5 Maxwell volumetric Q; 201x201 coarse nodal density to "
            "200x200 thermal cells; rho-dependent design kappa and TaIrTe4/design G"
        ),
        "gates": {
            "mapping_transpose_error_max": 1e-12,
            "linear_mapping_FD_error_max": 1e-8,
            "thermal_material_AD_FD_relative_error_max": 0.01,
            "linear_residual_max": 1e-8,
            "energy_balance_error_max": 0.01,
        },
        "preserved_diagnostic": {
            "scenario": "grown_grown",
            "raw_status": grown["raw_status_preserved"],
            "reason": (
                "The immutable raw run combined a 1e-12 transpose gate with a "
                "too-small 1e-5 mapping FD subtraction. Its observed mapping FD "
                "error 2.621e-11 already passes the separately specified 1e-8 "
                "linear-mapping FD gate; no solver output or gradient was rescaled."
            ),
        },
        "cases": cases,
        "optimization_iterations": 0,
        "Maxwell_Q_gradient_included": False,
        "empirical_normalization_or_gradient_rescaling": False,
    }
    RESULTS.mkdir(parents=True, exist_ok=True)
    PLOTS.mkdir(parents=True, exist_ok=True)
    summary_path = RESULTS / "production_thermal_material_adfd_summary.json"
    summary_path.write_text(json.dumps(summary, indent=2) + "\n")

    rows = []
    for scenario, result in cases.items():
        for row in result["FD_step_sweep"]:
            rows.append(
                {
                    "scenario": scenario,
                    "step": row["step"],
                    "adjoint_directional_A": row["adjoint_directional_A"],
                    "finite_difference_directional_A": row["finite_difference_directional_A"],
                    "relative_error": row["relative_error"],
                    "worst_forward_residual": row["worst_forward_residual"],
                    "worst_energy_balance_error": row["worst_energy_balance_error"],
                    "clipping": row["clipping"],
                }
            )
    csv_path = RESULTS / "production_thermal_material_adfd_cases.csv"
    with csv_path.open("w", newline="") as handle:
        writer = csv.DictWriter(
            handle, fieldnames=list(rows[0]), lineterminator="\n"
        )
        writer.writeheader()
        writer.writerows(rows)

    fig, axes = plt.subplots(1, 3, figsize=(16, 4.8), constrained_layout=True)
    for scenario, marker in (("grown_grown", "o"), ("evaporated_evaporated", "s")):
        selected = [row for row in rows if row["scenario"] == scenario]
        axes[0].loglog([row["step"] for row in selected], [row["relative_error"] for row in selected], marker=marker, label=scenario)
    axes[0].axhline(0.01, color="black", linestyle=":", label="1% gate")
    axes[0].invert_xaxis()
    axes[0].set(xlabel="centered-FD step h", ylabel="relative AD-FD error", title="Thermal-material AD-FD")
    axes[0].legend()
    labels = ["grown/grown", "evap./evap."]
    axes[1].bar(np.arange(2) - 0.18, [cases[name]["gradient_norms"]["bulk_k"] for name in cases], 0.36, label="bulk kappa")
    axes[1].bar(np.arange(2) + 0.18, [cases[name]["gradient_norms"]["interface_G"] for name in cases], 0.36, label="interface G")
    axes[1].set_xticks(np.arange(2), labels)
    axes[1].set_yscale("log")
    axes[1].set(ylabel="nodal gradient L2 (A)", title="Gradient components")
    axes[1].legend()
    axes[2].scatter(
        [row["finite_difference_directional_A"] for row in rows],
        [row["adjoint_directional_A"] for row in rows],
        c=[row["step"] for row in rows],
        cmap="viridis",
        s=70,
    )
    values = np.asarray([row[key] for row in rows for key in ("finite_difference_directional_A", "adjoint_directional_A")])
    low, high = float(np.min(values)), float(np.max(values))
    axes[2].plot([low, high], [low, high], "k--", label="ideal AD=FD")
    axes[2].set(xlabel="finite-difference directional (A)", ylabel="adjoint directional (A)", title="Directional derivative parity")
    axes[2].legend()
    plot_path = PLOTS / "production_thermal_material_adfd.png"
    fig.savefig(plot_path, dpi=180)
    plt.close(fig)

    report_path = RESULTS / "PRODUCTION_THERMAL_MATERIAL_ADFD_REPORT.md"
    report_path.write_text(
        f"""# Production fixed-Q thermal-material AD-FD

Status: `{status}`

This checkpoint freezes the validated Maxwell volumetric Q and differentiates
only the thermal design-material branch: isotropic gray design kappa and the
TaIrTe4/design interface conductance. The 201x201 nodal density on the coarse
20 um canvas maps to 200x200 thermal cells by four-node cell averaging; its
exact transpose is used for the nodal gradient.

| scenario | selected h | AD-FD relative error | mapping dot error | mapping FD error | energy balance |
|---|---:|---:|---:|---:|---:|
| grown/grown | {grown['FD_step_sweep'][-1]['step']:.4g} | {grown['FD_step_sweep'][-1]['relative_error']:.6e} | {grown['published_mapping_worst_dot_error']:.6e} | {grown['published_mapping_worst_FD_error']:.6e} | {grown['energy_balance_error']:.6e} |
| evaporated/evaporated | {evaporated['FD_step_sweep'][0]['step']:.4g} | {evaporated['FD_step_sweep'][0]['relative_error']:.6e} | {evaporated['published_mapping_worst_dot_error']:.6e} | {evaporated['published_mapping_worst_FD_error']:.6e} | {evaporated['energy_balance_error']:.6e} |

The grown/grown raw result remains immutable with its original failed status.
That status came solely from combining a `1e-12` transpose gate with a
roundoff-sensitive `h=1e-5` mapping FD. Its physical AD-FD error converges from
`3.563e-5` to `2.229e-6` as `h` goes from `0.01` to `0.0025`. The published
gate separates mapping transpose (`1e-12`) from mapping FD (`1e-8`); no
empirical normalization or gradient rescaling was used.

This is not the combined optical/thermal gradient. Maxwell adjoint,
coarse-gradient window selection, latent filter/projection AD-FD, and
optimization remain blocked.
"""
    )
    manifest = json.loads(MANIFEST.read_text())
    manifest["production_fixed_Q_thermal_material_adfd"] = {
        "status": status,
        "raw_artifacts_committed_to_git": False,
        "cases": artifacts,
        "preserved_raw_failure": True,
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps({"status": status, "summary": str(summary_path), "csv": str(csv_path), "report": str(report_path), "plot": str(plot_path)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
